'use strict';
const VEHICLES = [
  {id:'auto',name:'Autos 0 km',category:'autos',image:'images/03_broker_auto_0km.jpg',alt:'Auto azul en sala de exhibición',text:'Para moverte todos los días o dar el próximo paso. Consultanos por las opciones de autos 0 km.'},
  {id:'pickup',name:'Pickups 0 km',category:'pickups',image:'images/04_broker_pickup_0km.jpg',alt:'Pickup blanca en exterior',text:'Opciones de pickups para trabajo, ruta y proyectos personales. Pedinos una propuesta a medida.'},
  {id:'moto',name:'Motos 0 km',category:'motos',image:'images/05_broker_moto_0km.jpg',alt:'Motocicleta negra en exhibición',text:'Buscá una moto 0 km y conocé las alternativas que podemos acercarte.'},
  {id:'suv',name:'SUV 0 km',category:'pickups',image:'images/06_broker_suv_0km.jpg',alt:'SUV plateada en exterior',text:'Más espacio y versatilidad para tu próxima etapa. Consultá por opciones SUV 0 km.'},
  {id:'camion',name:'Camiones 0 km',category:'camiones',image:'images/02_broker_horizontal_16x9.jpg',alt:'Camión blanco junto a otros vehículos',text:'Contanos qué tipo de camión necesitás y te acercamos una cotización personalizada.'}
];
const WA='5493804861905';
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const getVehicle=id=>VEHICLES.find(v=>v.id===id);
const Selection={KEY:'broker_vehicle_selection',get(){try{const data=JSON.parse(localStorage.getItem(this.KEY));return Array.isArray(data)?data.filter(id=>getVehicle(id)):[]}catch{return[]}},save(ids){localStorage.setItem(this.KEY,JSON.stringify([...new Set(ids)]));document.dispatchEvent(new Event('selection:updated'))},add(id){const ids=this.get();if(!ids.includes(id))ids.push(id);this.save(ids)},remove(id){this.save(this.get().filter(x=>x!==id))}};
function showToast(msg){let wrap=document.querySelector('.toast-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='toast-wrap';wrap.setAttribute('aria-live','polite');document.body.appendChild(wrap)}const toast=document.createElement('div');toast.className='toast';toast.setAttribute('role','status');toast.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 6L9 17l-5-5"/></svg><span>${esc(msg)}</span>`;wrap.appendChild(toast);setTimeout(()=>{toast.classList.add('hiding');setTimeout(()=>toast.remove(),220)},3200)}
function initModelBarScroll(){const bar=document.querySelector('.gw-modelos');if(!bar)return;let showTimer=0,frame=0;const update=()=>{frame=0;if(window.scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(showTimer);showTimer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)};addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(update)},{passive:true})}
function initWspFloat(){const btn=document.getElementById('wsp-float');if(!btn)return;let shown=false;window.addEventListener('scroll',()=>{if(window.scrollY>600&&!shown){shown=true;btn.classList.add('visible')}},{passive:true})}
function refreshMotion(){if(typeof ScrollTrigger!=='undefined')ScrollTrigger.refresh()}
function initReveals(){const els=[...document.querySelectorAll('[data-animate]')];if(!els.length)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){els.forEach(el=>el.classList.add('in'));return}document.documentElement.classList.add('js-motion');if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');io.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -20px 0px'});els.forEach(el=>io.observe(el))}else els.forEach(el=>el.classList.add('in'))}
function initNav(){const nav=document.getElementById('mainNav'),toggle=document.getElementById('menuToggle'),close=document.getElementById('navClose');if(!nav||!toggle)return;const mobile=matchMedia('(max-width: 830px)');const sync=()=>{if(!mobile.matches){nav.inert=false;nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll')}else if(!nav.classList.contains('open'))nav.inert=true};const shut=()=>{nav.classList.remove('open');nav.inert=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll');toggle.focus()};toggle.addEventListener('click',()=>{nav.inert=false;nav.classList.add('open');toggle.setAttribute('aria-expanded','true');document.body.classList.add('no-scroll');close.focus()});close.addEventListener('click',shut);nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',shut));mobile.addEventListener('change',sync);sync();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open'))shut()})}
let activeOverlay=null,returnFocus=null;
function openOverlay(el){if(activeOverlay)closeOverlay();returnFocus=document.activeElement;el.hidden=false;activeOverlay=el;document.body.classList.add('no-scroll');const first=el.querySelector('button[data-close],button,a');first?.focus()}
function closeOverlay(){if(!activeOverlay)return;activeOverlay.hidden=true;activeOverlay=null;document.body.classList.remove('no-scroll');returnFocus?.focus()}
function initOverlays(){document.querySelectorAll('.overlay').forEach(el=>{el.querySelectorAll('[data-close]').forEach(b=>b.addEventListener('click',closeOverlay))});document.addEventListener('keydown',e=>{if(!activeOverlay)return;if(e.key==='Escape'){closeOverlay();return}if(e.key==='Tab'){const focusables=[...activeOverlay.querySelectorAll('button:not([disabled]),a[href],input:not([disabled])')].filter(x=>x.offsetParent!==null);if(!focusables.length)return;const first=focusables[0],last=focusables.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}})}
function renderSelection(){const ids=Selection.get(),items=document.getElementById('selectionItems'),send=document.getElementById('sendSelection');document.getElementById('selectionCount').textContent=ids.length;document.getElementById('floatCount').textContent=ids.length;if(!ids.length){items.innerHTML='<p class="selection-empty">Todavía no sumaste vehículos. Explorá las categorías y agregá las que te interesen.</p>';send.classList.add('disabled');send.setAttribute('aria-disabled','true');send.href=`https://wa.me/${WA}`;return}items.innerHTML=ids.map(id=>{const v=getVehicle(id);return `<div class="selection-row"><strong>${esc(v.name)}</strong><button type="button" data-remove="${esc(id)}" aria-label="Quitar ${esc(v.name)}">Quitar</button></div>`}).join('');send.classList.remove('disabled');send.removeAttribute('aria-disabled');send.href=`https://wa.me/${WA}?text=${encodeURIComponent('Hola Broker, quiero consultar por: '+ids.map(id=>getVehicle(id).name).join(', ')+'. ¿Podrían pasarme modelos, disponibilidad y opciones de financiación?')}`;items.querySelectorAll('[data-remove]').forEach(btn=>btn.addEventListener('click',()=>Selection.remove(btn.dataset.remove)))}
function initSelection(){document.addEventListener('selection:updated',renderSelection);renderSelection();const overlay=document.getElementById('selectionOverlay');['openSelection','selectionFloat'].forEach(id=>document.getElementById(id)?.addEventListener('click',()=>openOverlay(overlay)))}
let selectedVehicle=null;
function showVehicle(id){const v=getVehicle(id);if(!v)return;selectedVehicle=v;const overlay=document.getElementById('vehicleOverlay');document.getElementById('modalTitle').textContent=v.name;document.getElementById('modalText').textContent=v.text;document.getElementById('modalWa').href=`https://wa.me/${WA}?text=${encodeURIComponent('Hola Broker, quiero consultar por '+v.name+'. ¿Podrían pasarme modelos, disponibilidad y opciones de financiación?')}`;const img=document.getElementById('modalImage');img.src=v.image;img.alt=v.alt;openOverlay(overlay)}
function initCatalog(){const grid=document.getElementById('vehicleGrid'),search=document.getElementById('catalogSearch'),filters=[...document.querySelectorAll('[data-filter]')];let category='todos',firstRender=true;const render=()=>{const query=search.value.trim().toLocaleLowerCase('es-AR');const list=VEHICLES.filter(v=>(category==='todos'||v.category===category)&&(v.name.toLocaleLowerCase('es-AR').includes(query)||v.text.toLocaleLowerCase('es-AR').includes(query)));grid.innerHTML=list.length?list.map(v=>`<article class="vehicle-card" data-animate><div class="card-image"><img src="${v.image}" alt="${esc(v.alt)}" loading="lazy" width="700" height="700"><span>0 km · Consultá</span></div><div class="card-copy"><h3>${esc(v.name)}</h3><p>${esc(v.text)}</p><div class="card-actions"><button type="button" data-detail="${v.id}">Ver detalles ↗</button><button type="button" class="add-card" data-add="${v.id}" aria-label="Sumar ${esc(v.name)} a mi consulta">+</button></div></div></article>`).join(''):'<p class="empty-results">No encontramos esa categoría. Probá con otra búsqueda o escribinos por WhatsApp.</p>';grid.querySelectorAll('[data-detail]').forEach(btn=>btn.addEventListener('click',()=>showVehicle(btn.dataset.detail)));grid.querySelectorAll('[data-add]').forEach(btn=>btn.addEventListener('click',()=>{Selection.add(btn.dataset.add);showToast('Se agregó a tu selección')}));if(!firstRender)grid.querySelectorAll('[data-animate]').forEach(el=>el.classList.add('in'));firstRender=false;refreshMotion()};filters.forEach(btn=>btn.addEventListener('click',()=>{category=btn.dataset.filter;filters.forEach(f=>{f.classList.toggle('active',f===btn);f.setAttribute('aria-pressed',String(f===btn))});render()}));search.addEventListener('input',render);document.getElementById('modalAdd').addEventListener('click',()=>{if(selectedVehicle){Selection.add(selectedVehicle.id);closeOverlay();showToast('Se agregó a tu selección')}});render()}
document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='f12'||(e.ctrlKey&&e.shiftKey&&['i','j','c'].includes(k))||(e.ctrlKey&&k==='u'))e.preventDefault()});
if(typeof gsap!=='undefined'&&typeof ScrollTrigger!=='undefined')gsap.registerPlugin(ScrollTrigger);if(typeof gsap==='undefined')document.querySelectorAll('[data-animate]').forEach(el=>el.classList.add('in'));if(typeof ScrollTrigger!=='undefined')window.addEventListener('load',()=>ScrollTrigger.refresh());
initModelBarScroll();initWspFloat();initNav();initOverlays();initSelection();initCatalog();initReveals();
