'use strict';
const IMAGE={group:'02_avanza_mas_horizontal_16x9.webp',cognitive:'03_avanza_mas_terapia_cognitiva.webp',home:'04_avanza_mas_acompanamiento_domiciliario.webp',digital:'05_avanza_mas_cursos_y_materiales_digitales.webp',community:'06_avanza_mas_comunidad_y_profesionales.webp'};
const OFFERS=[
  {id:'metodo-tres-pilares',type:'curso',kind:'Curso',category:'Método',title:'Método Jesica Gómez®: tres pilares',summary:'Una introducción a la mirada física, cognitiva y social.',description:'Recorré los ejes del método y explorá cómo organizar propuestas para personas mayores. El temario definitivo, la modalidad y el precio se confirmarán antes de publicar.',image:IMAGE.group,points:['Pilar físico: movimiento en contexto','Pilar cognitivo: actividades con propósito','Pilar social: participación y vínculo'],featured:true},
  {id:'actividades-cognitivas',type:'curso',kind:'Curso',category:'Cognitivo',title:'Actividades cognitivas para la vida diaria',summary:'Ideas para estimular memoria, atención y conversación.',description:'Una propuesta de formación de ejemplo para transformar actividades cotidianas en oportunidades de estimulación. Contenidos y duración a confirmar.',image:IMAGE.cognitive,points:['Planificación de actividades','Selección de recursos','Adaptación a cada contexto'],featured:true},
  {id:'movimiento-adaptado',type:'curso',kind:'Curso',category:'Físico',title:'Movimiento adaptado y participación',summary:'Recursos para incorporar el movimiento a los encuentros.',description:'Un recorrido ilustrativo por propuestas de movimiento y participación. El programa final se definirá junto a AVANZA+.',image:IMAGE.home,points:['Objetivos del encuentro','Opciones de movimiento','Registro y continuidad'],featured:true},
  {id:'taller-vinculo-social',type:'curso',kind:'Taller',category:'Social',title:'Taller de propuestas sociales',summary:'Dinámicas para conversar, compartir y crear vínculos.',description:'Vista de ejemplo para un próximo taller. Fecha, modalidad, programa y precio pendientes de confirmación.',image:IMAGE.community,points:['Actividades grupales','Participación significativa','Ideas para adaptar'],featured:true},
  {id:'banco-actividades',type:'digital',kind:'Material digital',category:'Recursos',title:'Banco de actividades imprimibles',summary:'Una biblioteca organizada por objetivos y pilares.',description:'Ejemplo de cómo se vendería y entregaría un material descargable. La selección final de archivos y el precio están pendientes.',image:IMAGE.digital,points:['Recursos por pilar','Material descargable','Acceso digital tras el pago en producción']},
  {id:'planificacion-semanal',type:'digital',kind:'Material digital',category:'Recursos',title:'Guía de planificación semanal',summary:'Una estructura para preparar encuentros con claridad.',description:'Material demostrativo para mostrar el formato de venta digital. El contenido definitivo se cargará antes del lanzamiento.',image:IMAGE.cognitive,points:['Objetivos de cada encuentro','Secuencia de actividades','Notas de seguimiento']},
  {id:'fichas-sociales',type:'digital',kind:'Material digital',category:'Recursos',title:'Fichas de conversación y vínculo',summary:'Disparadores para participar y compartir recuerdos.',description:'Ejemplo de recurso digital. La cantidad de fichas, el contenido y el precio se confirmarán en producción.',image:IMAGE.community,points:['Conversaciones guiadas','Actividades en grupo','Formato descargable']},
  {id:'tarjetas-actividades',type:'fisico',kind:'Material físico',category:'Recursos',title:'Tarjetas para actividades',summary:'Un formato físico para llevar propuestas a cada encuentro.',description:'Presentación ilustrativa de un posible material físico. La composición, el precio y la entrega se definirán antes de la venta.',image:IMAGE.cognitive,points:['Material para usar en encuentros','Contenido a confirmar','Entrega a coordinar en producción']}
];
const PROFILES=[{id:'p1',profession:'Acompañamiento',zone:'CABA'},{id:'p2',profession:'Terapia ocupacional',zone:'Zona Sur'},{id:'p3',profession:'Kinesiología',zone:'Zona Norte'},{id:'p4',profession:'Acompañamiento',zone:'Zona Oeste'}];
const KEY='avanzamas_cart_demo_v1';const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const state={type:'',query:'',cart:[],lastFocus:null,modalId:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const image=o=>`images/${encodeURIComponent(o.image)}`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3600)}
function card(o){return `<article class="offer-card"><button type="button" class="offer-photo" data-offer="${esc(o.id)}" aria-label="Ver ${esc(o.title)}"><img src="${image(o)}" alt="${esc(o.title)}" loading="lazy"><span>${esc(o.kind)}</span></button><div class="offer-info"><small>${esc(o.category)}</small><h3>${esc(o.title)}</h3><p>${esc(o.summary)}</p><button type="button" data-offer="${esc(o.id)}">Ver propuesta ↗</button></div></article>`}
function initCatalog(){const featured=$('#featured-grid'),grid=$('#catalog-grid');featured.innerHTML=OFFERS.filter(o=>o.featured).map(card).join('');const render=()=>{const found=OFFERS.filter(o=>(!state.type||o.type===state.type)&&norm([o.title,o.summary,o.description,o.category,o.kind].join(' ')).includes(norm(state.query)));grid.innerHTML=found.length?found.map(card).join(''):'<div class="catalog-empty"><h3>No encontramos esa propuesta</h3><p>Probá otra palabra o mirá toda la oferta.</p><button type="button" data-clear>Ver todo</button></div>';$('#catalog-count').textContent=`${found.length} ${found.length===1?'propuesta':'propuestas'} de ejemplo`;$('#clear-filters').hidden=!state.type&&!state.query};const clear=()=>{state.type='';state.query='';$('#catalog-search').value='';$$('[data-type]').forEach(b=>b.classList.toggle('active',b.dataset.type===''));render()};$$('[data-type]').forEach(b=>b.addEventListener('click',()=>{state.type=b.dataset.type;$$('[data-type]').forEach(x=>x.classList.toggle('active',x===b));render()}));$('#catalog-search').addEventListener('input',e=>{state.query=e.target.value.trim();render()});$('#clear-filters').addEventListener('click',clear);grid.addEventListener('click',e=>{if(e.target.closest('[data-clear]'))clear()});for(const parent of [featured,grid])parent.addEventListener('click',e=>{const b=e.target.closest('[data-offer]');if(b)openOffer(b.dataset.offer)});render()}
function initDirectory(){const grid=$('#directory-grid');const render=()=>{const zone=$('#zone-filter').value,profession=$('#profession-filter').value;const found=PROFILES.filter(p=>(!zone||p.zone===zone)&&(!profession||p.profession===profession));grid.innerHTML=found.length?found.map((p,i)=>`<article class="profile-card"><span>PERFIL DE EJEMPLO ${String(i+1).padStart(2,'0')}</span><h4>${esc(p.profession)}</h4><p>Atención a domicilio · ${esc(p.zone)}</p><a href="https://wa.me/5491126157480?text=${encodeURIComponent(`Hola AVANZA+, busco ${p.profession} en ${p.zone}`)}" target="_blank" rel="noopener">Consultar por esta búsqueda ↗</a></article>`).join(''):'<div class="directory-empty">No hay perfiles de muestra con esos filtros. Probá otra zona o profesión.</div>';$('#directory-count').textContent=`${found.length} ${found.length===1?'perfil de muestra':'perfiles de muestra'}`};$('#zone-filter').addEventListener('change',render);$('#profession-filter').addEventListener('change',render);render()}
function readCart(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(raw)?raw.filter(x=>typeof x==='string'&&OFFERS.some(o=>key(o)===x)).slice(0,30):[]}catch{return[]}}
function key(o){return `${o.type==='curso'?'course':'product'}:${o.id}`}
function saveCart(){localStorage.setItem(KEY,JSON.stringify(state.cart));renderCart()}
function renderCart(){const count=state.cart.length;$$('[data-cart-count]').forEach(x=>x.textContent=count);$('.floating-actions').classList.toggle('visible',count>0||scrollY>550);const groups=[['Acceso digital',state.cart.filter(k=>!k.startsWith('product:tarjetas-actividades'))],['Material físico',state.cart.filter(k=>k==='product:tarjetas-actividades')]];$('#cart-items').innerHTML=count?groups.map(([label,keys])=>keys.length?`<div class="cart-group">${label}</div>${keys.map(k=>{const o=OFFERS.find(x=>key(x)===k);return `<div class="cart-row"><img src="${image(o)}" alt=""><div><strong>${esc(o.title)}</strong><small>${esc(o.kind)} · precio a confirmar</small></div><button type="button" data-remove="${esc(k)}">Quitar</button></div>`}).join('')}`:'').join(''):'<div class="catalog-empty"><h3>Tu selección está vacía</h3><p>Explorá las propuestas y sumá las que te interesen.</p><button type="button" data-cart-close>Volver al catálogo</button></div>'}
function addOffer(id){const o=OFFERS.find(x=>x.id===id);if(!o)return;const k=key(o);if(state.cart.includes(k)){toast('Esa propuesta ya está en tu selección.');return}state.cart.push(k);saveCart();toast(`${o.title} se sumó a tu selección.`)}
function openLayer(el){state.lastFocus=document.activeElement;$('#overlay').hidden=false;el.hidden=false;document.body.classList.add('no-scroll');$('.floating-actions').style.visibility='hidden';el.querySelector('button')?.focus()}
function closeLayers(){$('#overlay').hidden=true;$('#offer-modal').hidden=true;$('#cart-drawer').hidden=true;document.body.classList.remove('no-scroll');$('.floating-actions').style.visibility='';const url=new URL(location.href);url.searchParams.delete('curso');history.replaceState(null,'',url);state.lastFocus?.focus()}
function openOffer(id){const o=OFFERS.find(x=>x.id===id);if(!o)return;state.modalId=id;const digital=o.type!=='fisico';$('#offer-modal-body').innerHTML=`<div class="modal-layout"><img src="${image(o)}" alt="${esc(o.title)}"><div class="modal-copy"><span class="index-label">${esc(o.kind)} · ${esc(o.category)}</span><h2>${esc(o.title)}</h2><p>${esc(o.description)}</p><strong>Vista del contenido</strong><ul>${o.points.map(p=>`<li>${esc(p)}</li>`).join('')}</ul><p class="modal-note">Propuesta de demo. El precio, los archivos y ${digital?'el acceso':'la entrega'} se confirmarán antes de publicar.</p><button type="button" id="modal-add" class="button button-gold">Sumar a mi selección ↗</button></div></div>`;openLayer($('#offer-modal'));const url=new URL(location.href);url.searchParams.set('curso',id);history.replaceState(null,'',url)}
function initLayers(){state.cart=readCart();renderCart();$$('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>openLayer($('#cart-drawer'))));$$('[data-close]').forEach(b=>b.addEventListener('click',closeLayers));$('#overlay').addEventListener('click',closeLayers);$('#cart-items').addEventListener('click',e=>{const rem=e.target.closest('[data-remove]');if(rem){state.cart=state.cart.filter(x=>x!==rem.dataset.remove);saveCart()}if(e.target.closest('[data-cart-close]')){closeLayers();$('#catalogo').scrollIntoView()}});$('#offer-modal-body').addEventListener('click',e=>{if(e.target.closest('#modal-add')){addOffer(state.modalId);closeLayers()}});$('#checkout-preview').addEventListener('click',()=>toast('En producción, el pago habilitará el acceso digital automáticamente. Esta demo todavía no procesa pagos.'));addEventListener('keydown',e=>{const layer=!$('#offer-modal').hidden?$('#offer-modal'):!$('#cart-drawer').hidden?$('#cart-drawer'):null;if(!layer)return;if(e.key==='Escape'){closeLayers();return}if(e.key==='Tab'){const focus=[...layer.querySelectorAll('button:not([disabled]),a[href],input')];if(!focus.length)return;const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});addEventListener('scroll',()=>$('.floating-actions').classList.toggle('visible',state.cart.length>0||scrollY>550),{passive:true});const id=new URL(location.href).searchParams.get('curso');if(id&&OFFERS.some(o=>o.id===id))openOffer(id)}
function initNav(){const b=$('.menu-toggle'),nav=$('.main-nav');b.addEventListener('click',()=>{const open=nav.classList.toggle('open');b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');b.setAttribute('aria-expanded','false')}})}
function initModelBar(){const bar=$('.gw-modelos');let frame=0,timer=0;addEventListener('scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(timer);timer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)})},{passive:true})}
function initReveals(){const nodes=$$('[data-animate]');if(matchMedia('(prefers-reduced-motion: reduce)').matches){nodes.forEach(n=>n.classList.add('in'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:0,rootMargin:'0px 0px 80px 0px'});nodes.forEach(n=>io.observe(n))}
initCatalog();initDirectory();initLayers();initNav();initModelBar();initReveals();
