const NEGOCIO = {
  nombre: 'Lomitería Popular',
  sucursal: 'Valle Escondido',
  ciudad: 'Córdoba',
  whatsapp: '5493513657464',
  instagram: 'https://www.instagram.com/lomiteriapopularrn',
  horario: 'Todos los días de 8:00 a 00:00',
  envioGratisDesde: 35000,
};

const CATEGORIAS = [
  { id: 'lomitos', nombre: 'Lomitos', kicker: 'La casa', modo: 'foto', img: 'images/lomito-clasico-1200x1200.webp', bajada: 'El pan, el lomo y la mayonesa casera. Todos vienen con papas.' },
  { id: 'hamburguesas', nombre: 'Hamburguesas', kicker: 'Doble medallón', modo: 'foto', img: 'images/burger-tasty-1200x1200.webp', bajada: 'Cheddar de verdad, pan de papa y salsa popular.' },
  { id: 'milanesas', nombre: 'Milanesas', kicker: 'Ternera o pollo', modo: 'foto', img: 'images/milanesa-clasica-1200x1200.webp', bajada: 'Finita, dorada y con papas. Como corresponde.' },
  { id: 'sandwiches', nombre: 'Sándwiches', kicker: 'Del mundo', modo: 'foto', img: 'images/vacio-braseado-1200x1200.webp', bajada: 'Vacío braseado, tostados y clásicos de mostrador.' },
  { id: 'alplato', nombre: 'Al plato', kicker: 'Con guarnición', modo: 'foto', img: 'images/bife-lomo-plato-1200x1200.webp', bajada: 'Bifes y tartas sin TACC con ensalada y papas fritas.' },
  { id: 'papas', nombre: 'Papas y picadas', kicker: 'Para compartir', modo: 'foto', img: 'images/papas-bowl-1200x1200.webp', bajada: 'Papas con cheddar, nuggets, bastoncitos y empanadas.' },
  { id: 'ensaladas', nombre: 'Ensaladas', kicker: 'Frescas', modo: 'foto', img: 'images/ensalada-clasica-1200x1200.webp', bajada: 'Hojas verdes, aderezos caseros y proteína a elección.' },
  { id: 'desayunos', nombre: 'Desayunos', kicker: 'Desde las 8', modo: 'foto', img: 'images/desayuno-completo-1200x1200.webp', bajada: 'Infusión, tostadas, medialunas y jugo recién exprimido.' },
  { id: 'dulces', nombre: 'Dulces', kicker: 'El final', modo: 'foto', img: 'images/postre-vasos-1200x1200.webp', bajada: 'Brownie con helado, chocotorta, tiramisú y paletas.' },
  { id: 'combos', nombre: 'Combos y menús', kicker: 'Rinde más', modo: 'foto', img: 'images/mesa-completa-1600x1300.webp', bajada: 'Menús armados y combos para dos con bebida incluida.' },
  { id: 'bebidas', nombre: 'Bebidas', kicker: 'Bien frías', modo: 'lista', img: '', bajada: 'Gaseosas, aguas, jugos exprimidos y café de máquina.' },
  { id: 'cervezas', nombre: 'Cervezas y vinos', kicker: 'Para la mesa', modo: 'lista', img: '', bajada: 'Tirada, botella, espumantes y carta de vinos por copa.' },
];

const PRODUCTOS = [
  { id: 'lomito-clasico', cat: 'lomitos', nombre: 'Lomito Clásico', precio: 24000, img: 'images/lomito-clasico-1200x1200.webp', badge: 'El más pedido', destacado: true, tags: ['lomo', 'pollo', 'huevo', 'papas'], desc: 'Pan clásico o de pizza, lomo o bife de pollo, jamón, queso tybo, huevo, lechuga, tomate y mayonesa casera. Viene con papas.' },
  { id: 'lomito-milanesa', cat: 'lomitos', nombre: 'Lomito de Milanesa', precio: 22000, img: 'images/lomito-milanesa-1200x1200.webp', tags: ['milanesa', 'carne', 'pollo', 'papas'], desc: 'Pan, milanesa de carne o pollo, queso tybo, jamón cocido, huevo, lechuga, tomate y mayonesa casera. Viene con papas.' },
  { id: 'lomito-americano', cat: 'lomitos', nombre: 'Lomito Americano', precio: 24800, img: 'images/lomito-americano-1200x1200.webp', badge: 'Con panceta', destacado: true, tags: ['panceta', 'cheddar', 'barbacoa'], desc: 'Pan, lomo o bife de pollo, panceta, huevo revuelto, queso cheddar, cebolla morada, barbacoa y mayonesa casera. Viene con papas.' },
  { id: 'lomito-vegetariano', cat: 'lomitos', nombre: 'Lomito Vegetariano', precio: 18000, img: 'images/lomito-veggie-1200x1200.webp', badge: 'Veggie', tags: ['vegetariano', 'berenjena', 'zucchini'], desc: 'Pan, berenjenas y zucchinis grillados, cebolla salteada, queso tybo, huevo, lechuga, tomate y mayonesa casera. Viene con papas.' },
  { id: 'popular-xl', cat: 'lomitos', nombre: 'Popular Clásico XL', precio: 30400, img: 'images/lomito-xl-1200x1200.webp', badge: 'Para dos', destacado: true, tags: ['xl', 'compartir', 'lomo'], desc: 'Pan clásico, lomo de 160 g, jamón, queso tybo, huevo, lechuga, tomate y mayonesa casera. Viene con papas. Ideal para compartir.' },

  { id: 'burger-tasty', cat: 'hamburguesas', nombre: 'Tasty Clásica Burger', precio: 19500, img: 'images/burger-tasty-1200x1200.webp', badge: 'Cuádruple cheddar', destacado: true, tags: ['cheddar', 'bacon', 'pan de papa'], desc: 'Pan de papa, doble medallón de carne, cuádruple queso cheddar, bacon, lechuga, pepinillos y salsa popular. Viene con papas.' },
  { id: 'burger-doble', cat: 'hamburguesas', nombre: 'Doble Cheeseburger', precio: 18200, img: 'images/burger-doble-1200x1200.webp', tags: ['cheddar', 'doble medallón'], desc: 'Doble medallón de carne, cheddar y salsa tasty. Viene con papas.' },
  { id: 'burger-miercoles', cat: 'hamburguesas', nombre: 'Doble Cheeseburger de los Miércoles', precio: 18200, descuento: 36, img: 'images/burger-combo-1200x1200.webp', badge: 'Solo miércoles', destacado: true, tags: ['promo', 'miércoles', 'cheddar'], desc: 'La misma Doble Cheeseburger con precio de miércoles. Promoción válida únicamente los días miércoles.' },

  { id: 'milanesa-clasica', cat: 'milanesas', nombre: 'Milanesa Clásica', precio: 21500, img: 'images/milanesa-clasica-1200x1200.webp', destacado: true, tags: ['ternera', 'pollo', 'papas fritas'], desc: 'Milanesa de ternera o suprema de pollo. Acompañada con ensalada y papas fritas.' },
  { id: 'milanesa-caballo', cat: 'milanesas', nombre: 'Milanesa a Caballo', precio: 22200, img: 'images/milanesa-grande-1200x1200.webp', tags: ['huevo frito', 'ternera', 'pollo'], desc: 'Milanesa de ternera o suprema de pollo con dos huevos fritos. Acompañada con ensalada y papas fritas.' },
  { id: 'milanesa-napolitana', cat: 'milanesas', nombre: 'Milanesa Napolitana', precio: 23500, img: 'images/milanesa-napo-1200x1200.webp', badge: 'Clásico', tags: ['napolitana', 'mozzarella', 'jamón'], desc: 'Milanesa de ternera o suprema de pollo, salsa de tomate, jamón y queso mozzarella, pimiento rojo asado. Acompañada con ensalada y papas.' },

  { id: 'vacio-braseado', cat: 'sandwiches', nombre: 'Vacío Braseado y Vegetales', precio: 21000, img: 'images/vacio-braseado-1200x1200.webp', badge: 'Recomendado', destacado: true, tags: ['vacío', 'mayo chimi', 'tybo'], desc: 'Pan, vacío desmechado, doble queso tybo, vegetales salteados, tomate y mayo chimi. Viene con papas.' },
  { id: 'tostado-popular', cat: 'sandwiches', nombre: 'Tostado Popular', precio: 9000, img: 'images/tostado-popular-1200x1200.webp', tags: ['tostado', 'jamón', 'queso'], desc: 'Jamón cocido, queso fundido, lechuga, tomates confitados y mayonesa casera, servido en nuestro pan de la casa.' },
  { id: 'sandwich-jamon', cat: 'sandwiches', nombre: 'Sándwich de Jamón Cocido', precio: 9700, img: 'images/sandwich-jamon-1200x1200.webp', tags: ['jamón', 'queso', 'simple'], desc: 'Un clásico sencillo con jamón, queso y mayonesa.' },

  { id: 'bife-lomo-plato', cat: 'alplato', nombre: 'Bife de Lomo al Plato', precio: 23300, img: 'images/bife-lomo-plato-1200x1200.webp', destacado: true, tags: ['lomo', 'huevo', 'papas fritas'], desc: 'Bife de lomo de 160 g con jamón, queso tybo y huevo. Acompañado con ensalada y papas fritas.' },
  { id: 'bife-pollo-plato', cat: 'alplato', nombre: 'Bife de Pollo al Plato', precio: 20300, img: 'images/bife-pollo-plato-1200x1200.webp', tags: ['pollo', 'huevo', 'papas fritas'], desc: 'Bife de pollo con jamón, queso tybo y huevo. Acompañado con ensalada y papas fritas.' },
  { id: 'tarta-jyq', cat: 'alplato', nombre: 'Tarta sin TACC de Jamón y Queso', precio: 14000, img: 'images/tarta-jyq-1200x1200.webp', badge: 'Sin TACC', tags: ['sin tacc', 'celíaco', 'tarta'], desc: 'Jamón cocido, queso mozzarella y queso holanda. Masa sin TACC.' },
  { id: 'tarta-espinaca', cat: 'alplato', nombre: 'Tarta sin TACC de Espinaca', precio: 14000, img: 'images/tarta-espinaca-1200x1200.webp', badge: 'Sin TACC', tags: ['sin tacc', 'celíaco', 'vegetariano'], desc: 'Espinaca, queso mozzarella, salsa blanca, cebolla y morrones. Masa sin TACC.' },

  { id: 'papas-cheddar', cat: 'papas', nombre: 'Papas con Cheddar', precio: 10100, img: 'images/papas-cheddar-1200x1200.webp', badge: 'Para compartir', destacado: true, tags: ['cheddar', 'panceta', 'verdeo'], desc: 'Papas con cheddar, panceta y verdeo.' },
  { id: 'papas-clasicas', cat: 'papas', nombre: 'Papas Clásicas', precio: 7800, img: 'images/papas-clasicas-1200x1200.webp', tags: ['papas', 'fritas'], desc: 'Papas fritas cortadas y fritas al momento.' },
  { id: 'papas-huevo', cat: 'papas', nombre: 'Papas con Huevo', precio: 8600, img: 'images/papas-huevo-1200x1200.webp', tags: ['huevo revuelto', 'papas'], desc: 'Papas con huevo revuelto.' },
  { id: 'nuggets', cat: 'papas', nombre: 'Nuggets (5 unidades)', precio: 7800, img: 'images/nuggets-1200x1200.webp', tags: ['pollo', 'nuggets', 'chicos'], desc: 'Cinco nuggets de pollo rebozados y fritos.' },
  { id: 'nuggets-papas', cat: 'papas', nombre: 'Nuggets con Papas', precio: 12400, img: 'images/nuggets-papas-1200x1200.webp', tags: ['pollo', 'papas', 'chicos'], desc: 'Nuggets de pollo acompañados con una porción de papas fritas.' },
  { id: 'bastoncitos', cat: 'papas', nombre: 'Bastoncitos de Mozzarella (5 u.)', precio: 9300, img: 'images/bastoncitos-1200x1200.webp', tags: ['mozzarella', 'rebozado'], desc: 'Cinco bastoncitos de mozzarella rebozados, fritos y bien fundidos.' },
  { id: 'empanada-carne', cat: 'papas', nombre: 'Empanada de Carne', precio: 3100, img: 'images/empanada-carne-1200x1200.webp', tags: ['empanada', 'carne', 'unidad'], desc: 'Empanada de carne cortada a cuchillo. Precio por unidad.' },
  { id: 'empanada-jyq', cat: 'papas', nombre: 'Empanada de Jamón y Queso', precio: 3100, img: 'images/empanada-jyq-1200x1200.webp', tags: ['empanada', 'jamón', 'unidad'], desc: 'Empanada de jamón y queso. Precio por unidad.' },
  { id: 'empanada-verdura', cat: 'papas', nombre: 'Empanada de Verdura', precio: 3100, img: 'images/empanada-verdura-1200x1200.webp', tags: ['empanada', 'verdura', 'vegetariano'], desc: 'Empanada de verdura. Precio por unidad.' },

  { id: 'ensalada-clasica', cat: 'ensaladas', nombre: 'Ensalada Clásica', precio: 10200, img: 'images/ensalada-clasica-1200x1200.webp', tags: ['verde', 'huevo', 'choclo'], desc: 'Mix de hojas verdes, tomate, zanahoria, huevo, choclo y queso tybo.' },
  { id: 'ensalada-nuestra-caesar', cat: 'ensaladas', nombre: 'Nuestra Caesar', precio: 12700, img: 'images/ensalada-caesar-1200x1200.webp', badge: 'Con pollo crispy', destacado: true, tags: ['caesar', 'pollo', 'parmesano'], desc: 'Lechuga, croutons, queso parmesano y aderezo césar. Con pollo a la plancha o crispy.' },
  { id: 'ensalada-caesar', cat: 'ensaladas', nombre: 'Caesar', precio: 12700, img: 'images/ensalada-pollo-1200x1200.webp', tags: ['caesar', 'pollo grillado'], desc: 'Mix de hojas verdes, pechuga de pollo grillada, queso, aderezo caesar y croutones.' },
  { id: 'ensalada-palta', cat: 'ensaladas', nombre: 'Palta y Queso Azul', precio: 13800, img: 'images/ensalada-palta-1200x1200.webp', tags: ['palta', 'queso azul', 'nueces'], desc: 'Palta, queso azul, mix de verdes, tomates, cebolla morada y nueces.' },
  { id: 'ensalada-piamontesa', cat: 'ensaladas', nombre: 'Piamontesa', precio: 10700, img: 'images/ensalada-bowl-1200x1200.webp', tags: ['pimientos', 'queso azul', 'nueces'], desc: 'Mix de hojas verdes, pimientos asados, queso azul y nueces.' },
  { id: 'ensalada-romana', cat: 'ensaladas', nombre: 'Romana', precio: 11200, img: 'images/ensalada-verde-1200x1200.webp', tags: ['olivas', 'rúcula', 'semillas'], desc: 'Mix de hojas verdes, tomates asados, queso tybo, olivas negras, aderezo de rúcula y semillas.' },
  { id: 'ensalada-silvestre', cat: 'ensaladas', nombre: 'Silvestre', precio: 11200, img: 'images/ensalada-clasica-1200x1200.webp', tags: ['hongos', 'rúcula', 'vegetariano'], desc: 'Mix de hojas verdes, tomate, hongos asados, queso y aderezo de rúcula.' },
  { id: 'ensalada-pechuga-limon', cat: 'ensaladas', nombre: 'Pechuga al Limón', precio: 12100, img: 'images/ensalada-pollo-1200x1200.webp', tags: ['pollo', 'limón', 'liviano'], desc: 'Pechuga al limón con ensalada clásica o de rúcula y un aderezo a elección.' },

  { id: 'desayuno-completo', cat: 'desayunos', nombre: 'Desayuno Completo', precio: 11200, img: 'images/desayuno-completo-1200x1200.webp', badge: 'El más pedido', destacado: true, tags: ['desayuno', 'medialunas', 'jugo'], desc: 'Infusión + 2 criollitos o 2 medialunas o tostadas de pan de campo o integral con semillas + queso blanco o manteca + dulce de leche o mermelada + ensalada de frutas chica + jugo de naranja.' },
  { id: 'desayuno-light', cat: 'desayunos', nombre: 'Desayuno Light', precio: 8600, img: 'images/desayuno-light-1200x1200.webp', tags: ['light', 'tostadas', 'frutas'], desc: 'Infusión + 2 tostadas de pan de campo o integral con semillas + queso blanco + mermelada casera + ensalada de frutas chica.' },
  { id: 'desayuno-proteico', cat: 'desayunos', nombre: 'Desayuno Proteico', precio: 16700, img: 'images/desayuno-proteico-1200x1200.webp', badge: 'Con palta', tags: ['proteico', 'huevo', 'palta'], desc: 'Infusión + 2 tostadas de pan de campo o integral con semillas + jamón cocido natural + queso en fetas + queso blanco + huevo o claras revueltas + frutos secos + palta.' },
  { id: 'desayuno-compartir', cat: 'desayunos', nombre: 'Popular para Compartir', precio: 23700, img: 'images/desayuno-compartir-1200x1200.webp', badge: 'Para dos', tags: ['compartir', 'dos personas', 'brunch'], desc: '2 infusiones + 2 jugos de naranja chicos + 4 tostadas de pan de campo o integral + manteca o queso blanco + panceta o jamón + queso en fetas + palta + huevo + ensalada de frutas.' },
  { id: 'granola-bowl', cat: 'desayunos', nombre: 'Granola Bowl', precio: 11400, img: 'images/granola-bowl-1200x1200.webp', tags: ['yogurt', 'granola', 'frutas'], desc: 'Yogurt natural + granola casera + frutas frescas + miel + infusión.' },
  { id: 'avocado-toast', cat: 'desayunos', nombre: 'Avocado Toast', precio: 9800, img: 'images/avocado-toast-1200x1200.webp', tags: ['palta', 'huevo revuelto'], desc: 'Pan de molde, queso crema, huevos revueltos y palta.' },
  { id: 'medialuna-grasa', cat: 'desayunos', nombre: 'Medialuna de Grasa', precio: 1600, modo: 'lista', tags: ['medialuna', 'unidad'], desc: 'Precio por unidad.' },
  { id: 'medialuna-manteca', cat: 'desayunos', nombre: 'Medialuna de Manteca', precio: 1600, modo: 'lista', tags: ['medialuna', 'unidad'], desc: 'Precio por unidad.' },
  { id: 'criollo', cat: 'desayunos', nombre: 'Criollo', precio: 1500, modo: 'lista', tags: ['criollito', 'unidad'], desc: 'Precio por unidad.' },

  { id: 'brownie-helado', cat: 'dulces', nombre: 'Brownie con Helado', precio: 9200, img: 'images/brownie-helado-1200x1200.webp', badge: 'Tibio', destacado: true, tags: ['brownie', 'helado', 'chocolate'], desc: 'Brownie tibio de chocolate servido con una bocha de helado.' },
  { id: 'chocotorta', cat: 'dulces', nombre: 'Chocotorta', precio: 8400, img: 'images/chocotorta-1200x1200.webp', tags: ['chocolate', 'dulce de leche'], desc: 'La clásica de chocolinas, dulce de leche y queso crema.' },
  { id: 'mousse-chocolate', cat: 'dulces', nombre: 'Mousse de Chocolate', precio: 8400, img: 'images/mousse-1200x1200.webp', tags: ['mousse', 'chocolate'], desc: 'Mousse de chocolate semiamargo con crema.' },
  { id: 'tiramisu', cat: 'dulces', nombre: 'Tiramisú', precio: 8400, img: 'images/tiramisu-1200x1200.webp', tags: ['tiramisú', 'café', 'cacao'], desc: 'Vainillas embebidas en café, crema de mascarpone y cacao amargo.' },
  { id: 'mini-avellanas', cat: 'dulces', nombre: 'Mini Avellanas y Chocolate', precio: 12100, modo: 'lista', tags: ['helado', 'mini'], desc: 'Helado mini pote.' },
  { id: 'mini-cookies', cat: 'dulces', nombre: 'Mini Cookies and Cream', precio: 12100, modo: 'lista', tags: ['helado', 'mini'], desc: 'Helado mini pote.' },
  { id: 'mini-ddl', cat: 'dulces', nombre: 'Mini Dulce de Leche', precio: 12100, modo: 'lista', tags: ['helado', 'mini'], desc: 'Helado mini pote.' },
  { id: 'mini-ddl-cookies', cat: 'dulces', nombre: 'Mini Dulce de Leche y Cookies', precio: 12100, modo: 'lista', tags: ['helado', 'mini'], desc: 'Helado mini pote.' },
  { id: 'paleta-minion', cat: 'dulces', nombre: 'Paleta Minion', precio: 5600, modo: 'lista', tags: ['paleta', 'helado', 'chicos'], desc: 'Paleta helada.' },
  { id: 'paleta-nocciola', cat: 'dulces', nombre: 'Paleta Nocciola', precio: 5300, modo: 'lista', tags: ['paleta', 'helado'], desc: 'Paleta helada.' },
  { id: 'paleta-oli-king', cat: 'dulces', nombre: 'Paleta Oli King', precio: 5600, modo: 'lista', tags: ['paleta', 'helado'], desc: 'Paleta helada.' },
  { id: 'paleta-pistacchio', cat: 'dulces', nombre: 'Paleta Pistacchio', precio: 14600, modo: 'lista', tags: ['paleta', 'helado', 'pistacho'], desc: 'Paleta helada de pistacho.' },

  { id: 'menu-lomito', cat: 'combos', nombre: 'Menú Lomito Clásico', precio: 24700, img: 'images/parrilla-lomitos-1600x1300.webp', badge: 'Menú armado', destacado: true, tags: ['menú', 'lomito', 'combo'], desc: 'Lomito Clásico con papas más bebida, listo para pedir sin pensarlo.' },
  { id: 'menu-milanesa', cat: 'combos', nombre: 'Menú Milanesa Clásica de Carne', precio: 20000, img: 'images/milanesa-ensalada-1200x1200.webp', tags: ['menú', 'milanesa', 'combo'], desc: 'Milanesa clásica de carne con guarnición más bebida.' },
  { id: 'menu-ensalada', cat: 'combos', nombre: 'Menú Ensalada', precio: 17200, img: 'images/ensalada-verde-1200x1200.webp', tags: ['menú', 'ensalada', 'liviano'], desc: 'Ensalada a elección más bebida.' },
  { id: 'menu-empanadas', cat: 'combos', nombre: 'Menú Empanadas', precio: 17200, img: 'images/empanada-carne-1200x1200.webp', tags: ['menú', 'empanadas'], desc: 'Docena chica de empanadas surtidas más bebida.' },
  { id: 'combo-argento', cat: 'combos', nombre: 'Combo Argento + Gaseosa', precio: 21500, img: 'images/plato-papas-1200x1200.webp', badge: 'Lunes a jueves', destacado: true, tags: ['combo', 'vacío', 'gaseosa'], desc: 'Vacío braseado con papas más gaseosa. Válido de lunes a jueves.' },
  { id: 'combo-mediano', cat: 'combos', nombre: 'Combo Mediano Delivery', precio: 36100, img: 'images/mesa-completa-1600x1300.webp', badge: 'Para dos', destacado: true, tags: ['combo', 'delivery', 'compartir'], desc: 'Dos lomos medianos clásicos más una gaseosa de 1,5 litros.' },
  { id: 'mini-lomo', cat: 'combos', nombre: 'Mini Lomo con Papas', precio: 13500, img: 'images/lomito-milanesa-1200x1200.webp', badge: 'Porción chica', tags: ['mini', 'chicos', 'papas'], desc: 'Versión chica del lomo, acompañada con papas.' },
  { id: 'cajita-popular', cat: 'combos', nombre: 'Cajita Popular', precio: 16900, img: 'images/nuggets-papas-1200x1200.webp', badge: 'Para los chicos', tags: ['chicos', 'juguete', 'cajita'], desc: 'Mini lomo, hamburguesa o nuggets acompañado con papas, bebida y juguete.' },
  { id: 'medallon-extra', cat: 'combos', nombre: 'Medallón Extra', precio: 2000, modo: 'lista', tags: ['adicional', 'medallón'], desc: 'Sumale un medallón de carne a cualquier hamburguesa.' },

  { id: 'cafe-chico', cat: 'bebidas', nombre: 'Café Chico', precio: 3100, modo: 'lista', sub: 'Café e infusiones', tags: ['café'], desc: 'Café de máquina.' },
  { id: 'cafe-doble', cat: 'bebidas', nombre: 'Café Doble', precio: 4200, modo: 'lista', sub: 'Café e infusiones', tags: ['café'], desc: 'Café de máquina doble.' },
  { id: 'cafe-cortado', cat: 'bebidas', nombre: 'Café / Cortado', precio: 3100, modo: 'lista', sub: 'Café e infusiones', tags: ['café', 'cortado'], desc: 'Café o cortado.' },
  { id: 'cafe-jarro', cat: 'bebidas', nombre: 'Café en Jarro', precio: 4600, modo: 'lista', sub: 'Café e infusiones', tags: ['café', 'jarro'], desc: 'Café en jarro.' },
  { id: 'mate-cocido', cat: 'bebidas', nombre: 'Mate Cocido', precio: 2800, modo: 'lista', sub: 'Café e infusiones', tags: ['mate cocido'], desc: 'Mate cocido.' },
  { id: 'jugo-naranja-chico', cat: 'bebidas', nombre: 'Jugo de Naranja Chico', precio: 3500, modo: 'lista', sub: 'Jugos y licuados', tags: ['jugo', 'naranja'], desc: 'Exprimido al momento.' },
  { id: 'jugo-naranja-grande', cat: 'bebidas', nombre: 'Jugo de Naranja Grande', precio: 4300, modo: 'lista', sub: 'Jugos y licuados', tags: ['jugo', 'naranja'], desc: 'Exprimido al momento.' },
  { id: 'licuado', cat: 'bebidas', nombre: 'Licuado', precio: 5500, modo: 'lista', sub: 'Jugos y licuados', tags: ['licuado', 'fruta'], desc: 'Licuado de fruta de estación.' },
  { id: 'pepsi-lata', cat: 'bebidas', nombre: 'Pepsi Lata 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['pepsi', 'lata'], desc: 'Lata 354 cc.' },
  { id: 'pepsi-black-lata', cat: 'bebidas', nombre: 'Pepsi Black Lata 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['pepsi', 'sin azúcar'], desc: 'Lata 354 cc.' },
  { id: 'pepsi-15', cat: 'bebidas', nombre: 'Pepsi 1,5 L', precio: 6500, modo: 'lista', sub: 'Gaseosas', tags: ['pepsi', 'litro'], desc: 'Botella 1,5 litros.' },
  { id: 'pepsi-black-15', cat: 'bebidas', nombre: 'Pepsi Black 1,5 L', precio: 6500, modo: 'lista', sub: 'Gaseosas', tags: ['pepsi', 'sin azúcar'], desc: 'Botella 1,5 litros.' },
  { id: 'mirinda-lata', cat: 'bebidas', nombre: 'Mirinda Lata 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['mirinda', 'naranja'], desc: 'Lata 354 cc.' },
  { id: 'mirinda-zero', cat: 'bebidas', nombre: 'Mirinda Zero 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['mirinda', 'zero'], desc: 'Lata 354 cc.' },
  { id: 'mirinda-15', cat: 'bebidas', nombre: 'Mirinda 1,5 L', precio: 6500, modo: 'lista', sub: 'Gaseosas', tags: ['mirinda', 'litro'], desc: 'Botella 1,5 litros.' },
  { id: 'sevenup-lata', cat: 'bebidas', nombre: 'Seven Up Lata 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['seven up', 'lima limón'], desc: 'Lata 354 cc.' },
  { id: 'sevenup-free', cat: 'bebidas', nombre: 'Seven Up Free Lata 354 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['seven up', 'free'], desc: 'Lata 354 cc.' },
  { id: 'paso-pomelo-lata', cat: 'bebidas', nombre: 'Paso de los Toros Pomelo 269 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['pomelo', 'amargo'], desc: 'Botella 269 cc.' },
  { id: 'paso-tonica-lata', cat: 'bebidas', nombre: 'Paso de los Toros Tónica 269 cc', precio: 4000, modo: 'lista', sub: 'Gaseosas', tags: ['tónica'], desc: 'Botella 269 cc.' },
  { id: 'paso-pomelo-15', cat: 'bebidas', nombre: 'Paso de los Toros Pomelo 1,5 L', precio: 6500, modo: 'lista', sub: 'Gaseosas', tags: ['pomelo', 'litro'], desc: 'Botella 1,5 litros.' },
  { id: 'paso-tonica-15', cat: 'bebidas', nombre: 'Paso de los Toros Tónica 1,5 L', precio: 6500, modo: 'lista', sub: 'Gaseosas', tags: ['tónica', 'litro'], desc: 'Botella 1,5 litros.' },
  { id: 'agua-sg-500', cat: 'bebidas', nombre: 'Agua sin gas 500 cc', precio: 4000, modo: 'lista', sub: 'Aguas', tags: ['agua'], desc: 'Botella 500 cc.' },
  { id: 'agua-cg-500', cat: 'bebidas', nombre: 'Agua con gas 500 cc', precio: 4000, modo: 'lista', sub: 'Aguas', tags: ['agua', 'gasificada'], desc: 'Botella 500 cc.' },
  { id: 'agua-sg-15', cat: 'bebidas', nombre: 'Agua sin gas 1,5 L', precio: 6800, modo: 'lista', sub: 'Aguas', tags: ['agua', 'litro'], desc: 'Botella 1,5 litros.' },
  { id: 'h2o-15', cat: 'bebidas', nombre: 'H2O 1,5 L', precio: 6800, modo: 'lista', sub: 'Aguas', tags: ['h2o', 'saborizada'], desc: 'Botella 1,5 litros.' },
  { id: 'limonada-vaso', cat: 'bebidas', nombre: 'Vaso de Limonada', precio: 4000, modo: 'lista', sub: 'Aguas', tags: ['limonada', 'casera'], desc: 'Limonada casera por vaso.' },
  { id: 'limonada-jarra', cat: 'bebidas', nombre: 'Jarra de Limonada', precio: 8600, modo: 'lista', sub: 'Aguas', tags: ['limonada', 'jarra'], desc: 'Jarra de limonada casera.' },
  { id: 'saborizada-limonada', cat: 'bebidas', nombre: 'Agua Saborizada Limonada 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },
  { id: 'saborizada-manzana', cat: 'bebidas', nombre: 'Agua Saborizada Manzana 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },
  { id: 'saborizada-naranja', cat: 'bebidas', nombre: 'Agua Saborizada Naranja 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },
  { id: 'saborizada-pera', cat: 'bebidas', nombre: 'Agua Saborizada Pera 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },
  { id: 'saborizada-pomelo-rosado', cat: 'bebidas', nombre: 'Agua Saborizada Pomelo Rosado 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },
  { id: 'saborizada-pomelo', cat: 'bebidas', nombre: 'Agua Saborizada Pomelo 500 cc', precio: 4000, modo: 'lista', sub: 'Saborizadas', tags: ['saborizada'], desc: 'Botella 500 cc.' },

  { id: 'stella-1l', cat: 'cervezas', nombre: 'Stella Artois 1 L', precio: 12500, modo: 'lista', sub: 'Cervezas', tags: ['stella', 'rubia'], desc: 'Botella 1 litro.' },
  { id: 'stella-noire-1l', cat: 'cervezas', nombre: 'Stella Artois Noire 1 L', precio: 12500, modo: 'lista', sub: 'Cervezas', tags: ['stella', 'negra'], desc: 'Botella 1 litro.' },
  { id: 'stella-monjita', cat: 'cervezas', nombre: 'Stella Artois Monjita 330 cc', precio: 5000, modo: 'lista', sub: 'Cervezas', tags: ['stella', 'porrón'], desc: 'Botella 330 cc.' },
  { id: 'stella-473', cat: 'cervezas', nombre: 'Stella Artois Rubia 473 cc', precio: 6900, modo: 'lista', sub: 'Cervezas', tags: ['stella', 'lata'], desc: 'Lata 473 cc.' },
  { id: 'stella-noire-473', cat: 'cervezas', nombre: 'Stella Artois Noire 473 cc', precio: 6900, modo: 'lista', sub: 'Cervezas', tags: ['stella', 'negra'], desc: 'Lata 473 cc.' },
  { id: 'stella-00', cat: 'cervezas', nombre: 'Stella 0.0 sin Alcohol 330 cc', precio: 5000, modo: 'lista', sub: 'Cervezas', tags: ['sin alcohol'], desc: 'Botella 330 cc sin alcohol.' },
  { id: 'andes-rubia-lt', cat: 'cervezas', nombre: 'Andes Origen Rubia 1 L', precio: 10300, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'rubia'], desc: 'Botella 1 litro.' },
  { id: 'andes-rubia-473', cat: 'cervezas', nombre: 'Andes Origen Rubia 473 cc', precio: 6400, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'lata'], desc: 'Lata 473 cc.' },
  { id: 'andes-ipa-lt', cat: 'cervezas', nombre: 'Andes Origen IPA 1 L', precio: 10300, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'ipa'], desc: 'Botella 1 litro.' },
  { id: 'andes-ipa-473', cat: 'cervezas', nombre: 'Andes Origen IPA 473 cc', precio: 6400, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'ipa'], desc: 'Lata 473 cc.' },
  { id: 'andes-negra-lt', cat: 'cervezas', nombre: 'Andes Origen Negra 1 L', precio: 10300, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'negra'], desc: 'Botella 1 litro.' },
  { id: 'andes-negra-473', cat: 'cervezas', nombre: 'Andes Origen Negra 473 cc', precio: 6400, modo: 'lista', sub: 'Cervezas', tags: ['andes', 'negra'], desc: 'Lata 473 cc.' },
  { id: 'patagonia-amber-473', cat: 'cervezas', nombre: 'Patagonia Amber Lager 473 cc', precio: 7300, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'amber'], desc: 'Lata 473 cc.' },
  { id: 'patagonia-amber-730', cat: 'cervezas', nombre: 'Patagonia Amber 730 cc', precio: 12700, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'amber'], desc: 'Botella 730 cc.' },
  { id: 'patagonia-bohemian-730', cat: 'cervezas', nombre: 'Patagonia Bohemian 730 cc', precio: 12700, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'bohemian'], desc: 'Botella 730 cc.' },
  { id: 'patagonia-porter-473', cat: 'cervezas', nombre: 'Patagonia Porter 473 cc', precio: 7300, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'porter'], desc: 'Lata 473 cc.' },
  { id: 'patagonia-porter-730', cat: 'cervezas', nombre: 'Patagonia Porter 730 cc', precio: 12700, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'porter'], desc: 'Botella 730 cc.' },
  { id: 'patagonia-ipa-473', cat: 'cervezas', nombre: 'Patagonia Vera IPA 473 cc', precio: 7300, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'ipa'], desc: 'Lata 473 cc.' },
  { id: 'patagonia-ipa-730', cat: 'cervezas', nombre: 'Patagonia Vera IPA 730 cc', precio: 12700, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'ipa'], desc: 'Botella 730 cc.' },
  { id: 'patagonia-247-473', cat: 'cervezas', nombre: 'Patagonia 24.7 473 cc', precio: 7300, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'session'], desc: 'Lata 473 cc.' },
  { id: 'patagonia-247-730', cat: 'cervezas', nombre: 'Patagonia 24.7 730 cc', precio: 12700, modo: 'lista', sub: 'Cervezas', tags: ['patagonia', 'session'], desc: 'Botella 730 cc.' },
  { id: 'coronita', cat: 'cervezas', nombre: 'Coronita 330 cc', precio: 7000, modo: 'lista', sub: 'Cervezas', tags: ['corona'], desc: 'Botella 330 cc.' },
  { id: 'michelob-ultra', cat: 'cervezas', nombre: 'Michelob Ultra sin TACC', precio: 6400, modo: 'lista', sub: 'Cervezas', tags: ['michelob', 'sin tacc'], desc: 'Cerveza sin TACC.' },
  { id: 'copa-malbec', cat: 'cervezas', nombre: 'Copa Las Perdices Malbec', precio: 5700, modo: 'lista', sub: 'Vino por copa', tags: ['copa', 'malbec'], desc: 'Vino por copa.' },
  { id: 'copa-chardonnay', cat: 'cervezas', nombre: 'Copa Las Perdices Chardonnay', precio: 5700, modo: 'lista', sub: 'Vino por copa', tags: ['copa', 'blanco'], desc: 'Vino por copa.' },
  { id: 'portillo-malbec', cat: 'cervezas', nombre: 'Portillo Malbec', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['malbec', 'tinto'], desc: 'Botella 750 cc.' },
  { id: 'portillo-sauvignon', cat: 'cervezas', nombre: 'Portillo Sauvignon Blanc', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['blanco'], desc: 'Botella 750 cc.' },
  { id: 'portillo-dulce', cat: 'cervezas', nombre: 'Portillo Dulce', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['dulce'], desc: 'Botella 750 cc.' },
  { id: 'portillo-rose', cat: 'cervezas', nombre: 'Portillo Rosé Malbec', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['rosado'], desc: 'Botella 750 cc.' },
  { id: 'novecento-malbec', cat: 'cervezas', nombre: 'Novecento Malbec', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['malbec', 'tinto'], desc: 'Botella 750 cc.' },
  { id: 'dolcezza-dulce', cat: 'cervezas', nombre: 'Dolcezza Dulce', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['dulce'], desc: 'Botella 750 cc.' },
  { id: 'dolcezza-rosado', cat: 'cervezas', nombre: 'Dolcezza Dulce Rosado', precio: 15300, modo: 'lista', sub: 'Vinos', tags: ['dulce', 'rosado'], desc: 'Botella 750 cc.' },
  { id: 'nieto-blend', cat: 'cervezas', nombre: 'Nieto Senetiner Blend Collection', precio: 22200, modo: 'lista', sub: 'Vinos', tags: ['blend', 'tinto'], desc: 'Botella 750 cc.' },
  { id: 'nieto-malbec', cat: 'cervezas', nombre: 'Nieto Senetiner Malbec', precio: 27100, modo: 'lista', sub: 'Vinos', tags: ['malbec', 'tinto'], desc: 'Botella 750 cc.' },
  { id: 'salentein-malbec', cat: 'cervezas', nombre: 'Salentein Reserva Malbec', precio: 27100, modo: 'lista', sub: 'Vinos', tags: ['malbec', 'reserva'], desc: 'Botella 750 cc.' },
  { id: 'salentein-rosado', cat: 'cervezas', nombre: 'Salentein Reserva Rosado de Syrah', precio: 27100, modo: 'lista', sub: 'Vinos', tags: ['rosado', 'reserva'], desc: 'Botella 750 cc.' },
  { id: 'fabre-malbec', cat: 'cervezas', nombre: 'Fabre Montmayou Reserva Malbec', precio: 25100, modo: 'lista', sub: 'Vinos', tags: ['malbec', 'reserva'], desc: 'Botella 750 cc.' },
  { id: 'santa-julia-chenin', cat: 'cervezas', nombre: 'Santa Julia Chenin Dulce', precio: 27100, modo: 'lista', sub: 'Vinos', tags: ['chenin', 'dulce'], desc: 'Botella 750 cc.' },
  { id: 'salentein-extra-brut', cat: 'cervezas', nombre: 'Salentein Extra Brut', precio: 22400, modo: 'lista', sub: 'Espumantes', tags: ['espumante', 'brut'], desc: 'Botella 750 cc.' },
  { id: 'salentein-brut-nature', cat: 'cervezas', nombre: 'Salentein Brut Nature', precio: 24000, modo: 'lista', sub: 'Espumantes', tags: ['espumante', 'nature'], desc: 'Botella 750 cc.' },
];
