const GW_PORTFOLIO = [
  {"url":"https://www.tesisenderecho.com.ar/","cat":"profesionales","name":"Tesis en Derecho","id":"tesisenderecho","accent":"#a30b4f"},
  {"url":"https://wa.me/5491140380678","cat":"gastronomia","name":"Moksha","id":"moksha","accent":"#d7b68a"},
  {"url":"https://www.sparrow.com.ar/","cat":"moda","name":"Sparrow","id":"sparrow","accent":"#d8d2c4"},
  {"url":"https://zaguirinmobiliaria.com.ar/","cat":"inmobiliaria","name":"Zaguir Inmobiliaria","id":"zaguirinmobiliaria","accent":"#d2b63f"},
  {"url":"https://www.cansuarconsultora.com.ar/","cat":"profesionales","name":"Cansuar Consultora","id":"cansuar","accent":"#e1704f"},
  {"url":"https://movilmarket.com.ar/","cat":"comercios","name":"Móvil Market","id":"mercadomovil","accent":"#f5279e"},
  {"url":"https://bfsoluciones.com/","cat":"profesionales","name":"BF Soluciones","id":"bfsoluciones","accent":"#7398c4"},
  {"url":"https://estudiopastore.com/","cat":"profesionales","name":"Estudio Pastore","id":"pastore","accent":"#708db8"},
  {"url":"https://lessence.com/","cat":"profesionales","name":"L'Essence","id":"lessence","accent":"#91a08a"},
  {"url":"https://www.instagram.com/analiasuarezfotografia/","cat":"profesionales","name":"Ana Suárez Fotografía","id":"anasuarez","accent":"#cbb8a6"},
  {"url":"https://casasentornquist.com.ar/","cat":"inmobiliaria","name":"Inmobiliaria Tornquist","id":"inmotorniquist","accent":"#45a06f"},
  {"url":"https://www.institutoculturapixel.com/","cat":"tecnologia","name":"Cultura Pixel","id":"culturapixel","accent":"#ed315f"},
  {"url":"https://infinitamente.com/","cat":"ecommerce","name":"InfinitaMente","id":"infinitamente","accent":"#35d4df"},
  {"url":"https://kare.com.ar/","cat":"ecommerce","name":"Kare","id":"kare","accent":"#a9bddc"},
  {"url":"https://locufre.com.ar/","cat":"ecommerce","name":"Locufre","id":"locufre","accent":"#c0d73e"},
  {"url":"https://lasmagnolias.com.ar/","cat":"ecommerce","name":"Las Magnolias","id":"lasmagnolias","accent":"#d98e9d"},
  {"url":"https://www.masmomentosunicos.com/","cat":"gastronomia","name":"Barra Tragos","id":"barratragos"},
  {"url":"http://ventoinmobiliaria.com.ar/","cat":"inmobiliaria","name":"Vento Inmobiliaria","id":"ventoinmobiliaria"},
  {"url":"https://www.psicorodas.com.ar/","cat":"profesionales","name":"Alder Psicología","id":"alderpsicologia"},
  {"url":"https://ahcd.org.ar/","cat":"profesionales","name":"AHCD","id":"ahcd"},
  {"url":"https://patagonianativa.vercel.app","cat":"profesionales","name":"Patagonia Nativa","id":"patagonianativa"},
  {"url":"https://tuproductoronline.vercel.app","cat":"profesionales","name":"Tu Productor Online","id":"tuproductoronline"},
  {"url":"https://tusencantosindumentaria.com.ar/","cat":"moda","name":"Tus Encantos","id":"tusencantos"},
  {"url":"https://www.danielsaire.com.ar/","cat":"comercios","name":"Daniel's Aire","id":"vendecursos"},
  {"url":"http://distririogrande.com.ar/","cat":"comercios","name":"Distrito Río Grande","id":"distribuidorariogrande"},
  {"url":"https://www.encantoestetica.com.ar/","cat":"profesionales","name":"Encanto Estética","id":"encantoestetica"},
  {"url":"https://www.zechtatuajes.com.ar","cat":"profesionales","name":"Zech Tatuajes","id":"tatuajes"},
  {"url":"https://experienciaki.com.ar/","cat":"profesionales","name":"Experiencia Ki","id":"experienciaki"},
  {"url":"https://www.hostelsrosarinos.com.ar/","cat":"profesionales","name":"Hostels Rosario","id":"hostels"},
  {"url":"https://licenciadaluena.com.ar","cat":"profesionales","name":"Psicóloga Luana","id":"psicologa"},
  {"url":"https://www.aisamsalud.com.ar/","cat":"profesionales","name":"Aisam Centro de Salud","id":"saludmental"},
  {"url":"https://tuprepagaonline.com.ar/","cat":"profesionales","name":"Prepaga Online","id":"prepagas"},
  {"url":"https://www.sanatoriosarmientosalud.com.ar/","cat":"profesionales","name":"Sanatorio Sarmiento","id":"sanatorio"},
  {"url":"https://www.urgencias24hs.com.ar/","cat":"profesionales","name":"Odontobosques","id":"odontobosques"},
  {"url":"https://www.estudioasilva.com.ar/","cat":"profesionales","name":"Estudio A. Silva","id":"abogadaaldana"},
  {"url":"https://agrimensurasatelital.com","cat":"profesionales","name":"Agrimensura Satelital","id":"agrimensura"},
  {"url":"https://italianosdelmundo.com.ar","cat":"profesionales","name":"Italianos del Mundo","id":"ciudadania"},
  {"url":"https://grupohv.com.ar","cat":"profesionales","name":"Grupo HV","id":"logistica"},
  {"url":"https://www.petit-app.com","cat":"tecnologia","name":"Petit App","id":"petit"},
  {"url":"https://bastonspaulete.com/","cat":"inmobiliaria","name":"Bastons Paulete","id":"consorcios"}
];
