'use strict';
const WA='5491150386519',KEY='fantasmaspesca_selection_demo_v1';
const IMG={reel:'03_los_fantasmas_de_la_pesca_reel_y_cana.webp',box:'04_los_fantasmas_de_la_pesca_caja_de_pesca.webp',accessories:'05_los_fantasmas_de_la_pesca_accesorios.webp',camp:'06_los_fantasmas_de_la_pesca_camping.webp'};
const PRODUCTS=[
 {id:'reel-frontal',name:'Reel frontal',category:'Reels y cañas',detail:'Una opción para armar tu equipo de pesca. Consultanos por modelos, medidas, precio y disponibilidad.',image:IMG.reel},
 {id:'reel-rotativo',name:'Reel rotativo',category:'Reels y cañas',detail:'Consultá qué modelos de reel rotativo están disponibles y cuál se adapta a tu tipo de pesca.',image:IMG.reel},
 {id:'cana-telescopica',name:'Caña telescópica',category:'Reels y cañas',detail:'Una categoría para elegir la caña adecuada a cada salida. Medidas y modelos a confirmar.',image:IMG.reel},
 {id:'cana-tramos',name:'Caña por tramos',category:'Reels y cañas',detail:'Cañas por tramos para distintas formas de pescar. Consultá las especificaciones de cada modelo.',image:IMG.reel},
 {id:'tanza',name:'Tanza para pesca',category:'Accesorios de pesca',detail:'Opciones de tanza según el equipo y el uso. Diámetros, presentación y precio a confirmar.',image:IMG.accessories},
 {id:'boyas',name:'Boyas',category:'Accesorios de pesca',detail:'Consultá diseños y presentaciones disponibles para armar tu línea.',image:IMG.accessories},
 {id:'plomadas',name:'Plomadas',category:'Accesorios de pesca',detail:'Plomadas para distintas configuraciones. Pesos y disponibilidad a confirmar.',image:IMG.accessories},
 {id:'senuelos',name:'Señuelos',category:'Accesorios de pesca',detail:'Señuelos para explorar distintas técnicas y escenarios. Modelos y colores a confirmar.',image:IMG.box},
 {id:'caja-pesca',name:'Caja de pesca',category:'Accesorios de pesca',detail:'Organizá señuelos, boyas y accesorios para llevar todo a mano. Formatos a confirmar.',image:IMG.box},
 {id:'pinza-ottoni',name:'Pinza Ottoni',category:'Accesorios de pesca',detail:'Consultá los modelos de pinzas Ottoni que se encuentren disponibles.',image:IMG.accessories},
 {id:'bolso-equipo',name:'Bolso para equipo',category:'Camping',detail:'Una opción de guardado para salidas de pesca y camping. Tamaños a confirmar.',image:IMG.camp},
 {id:'linterna-camping',name:'Linterna de camping',category:'Camping',detail:'Iluminación para la jornada al aire libre. Modelos y características a confirmar.',image:IMG.camp}
];
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];const state={category:'',query:'',shown:16,cart:[],lastFocus:null,product:null};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const img=p=>`images/${encodeURIComponent(p.image)}`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3000)}
function card(p){return `<article class="product-card"><button type="button" class="product-photo" data-detail="${esc(p.id)}" aria-label="Ver ${esc(p.name)}"><img src="${img(p)}" alt="${esc(p.name)}" loading="lazy"><span>VER DETALLE ↗</span></button><div class="product-info"><small>${esc(p.category)}</small><h3>${esc(p.name)}</h3><p>Precio y modelo a consultar</p><button type="button" class="button" data-add="${esc(p.id)}">Sumar a mi equipo</button></div></article>`}
function renderCatalog(){const matches=PRODUCTS.filter(p=>(!state.category||p.category===state.category)&&norm(`${p.name} ${p.category} ${p.detail}`).includes(norm(state.query)));$('#catalog-grid').innerHTML=matches.length?matches.slice(0,state.shown).map(card).join(''):'<div class="catalog-empty"><h3>No encontramos ese artículo</h3><p>Probá otra palabra o limpiá los filtros.</p><button type="button" data-clear>Ver todo el equipo</button></div>';$('#catalog-count').textContent=`${matches.length} ${matches.length===1?'artículo de ejemplo':'artículos de ejemplo'}`;$('#catalog-more').hidden=matches.length<=state.shown;$('#clear-filters').hidden=!state.category&&!state.query}
function setCategory(category){state.category=category;state.shown=16;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===category));renderCatalog();$('#catalogo').scrollIntoView({behavior:'smooth'})}
function initCatalog(){$$('[data-filter]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.filter)));$$('[data-category]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.category)));$('#catalog-search').addEventListener('input',e=>{state.query=e.target.value.trim();state.shown=16;renderCatalog()});const clear=()=>{state.query='';$('#catalog-search').value='';setCategory('')};$('#clear-filters').addEventListener('click',clear);$('#catalog-more').addEventListener('click',()=>{state.shown+=16;renderCatalog()});$('#catalog-grid').addEventListener('click',e=>{const b=e.target.closest('[data-detail]');if(b){openProduct(b.dataset.detail);return}const a=e.target.closest('[data-add]');if(a){addProduct(a.dataset.add);return}if(e.target.closest('[data-clear]'))clear()});renderCatalog()}
function readCart(){try{const raw=JSON.parse(localStorage.getItem(KEY)||'[]');return Array.isArray(raw)?raw.filter(x=>typeof x.id==='string'&&PRODUCTS.some(p=>p.id===x.id)&&Number.isInteger(x.qty)&&x.qty>0).slice(0,50):[]}catch{return[]}}
function saveCart(){localStorage.setItem(KEY,JSON.stringify(state.cart));renderCart()}
function cartMessage(){return `Hola Los Fantasmas de la Pesca, quiero consultar por estos artículos:\n${state.cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);return `• ${p.name} × ${x.qty}`}).join('\n')}\n¿Me confirman modelos, precios y disponibilidad?`}
function renderCart(){const count=state.cart.reduce((n,x)=>n+x.qty,0);$$('[data-cart-count]').forEach(el=>el.textContent=count);$('.floating-actions').classList.toggle('visible',count>0||scrollY>550);$('#cart-items').innerHTML=state.cart.length?state.cart.map(x=>{const p=PRODUCTS.find(y=>y.id===x.id);return `<div class="cart-row"><img src="${img(p)}" alt=""><div><strong>${esc(p.name)}</strong><small>Cantidad: ${x.qty}</small></div><button type="button" data-remove="${esc(x.id)}">Quitar</button></div>`}).join(''):'<div class="catalog-empty"><h3>Tu equipo está vacío</h3><p>Elegí artículos y te ayudamos con los detalles.</p><button type="button" data-cart-close>Volver al catálogo</button></div>';$('#cart-whatsapp').href=state.cart.length?`https://wa.me/${WA}?text=${encodeURIComponent(cartMessage())}`:`https://wa.me/${WA}?text=${encodeURIComponent('Hola Los Fantasmas de la Pesca, quiero consultar por sus artículos')}`}
function addProduct(id,qty=1){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;const item=state.cart.find(x=>x.id===id);if(item)item.qty=Math.min(99,item.qty+qty);else state.cart.push({id,qty});saveCart();toast(`${p.name} se sumó a tu equipo.`)}
function openLayer(el){state.lastFocus=document.activeElement;$('#overlay').hidden=false;el.hidden=false;document.body.classList.add('no-scroll');$('.floating-actions').style.visibility='hidden';el.querySelector('button')?.focus()}
function closeLayers(){$('#overlay').hidden=true;$('#cart-drawer').hidden=true;$('#product-modal').hidden=true;document.body.classList.remove('no-scroll');$('.floating-actions').style.visibility='';const url=new URL(location.href);url.searchParams.delete('producto');history.replaceState(null,'',url);state.lastFocus?.focus()}
function openProduct(id){const p=PRODUCTS.find(x=>x.id===id);if(!p)return;state.product=p;$('#modal-body').innerHTML=`<div class="modal-layout"><img src="${img(p)}" alt="${esc(p.name)}"><div class="modal-copy"><span class="eyebrow">${esc(p.category)}</span><h2>${esc(p.name)}</h2><p>${esc(p.detail)}</p><p>Esta ficha ilustra el catálogo. Te confirmamos marca, modelo, precio y disponibilidad antes de comprar.</p><button type="button" id="modal-add" class="button button-green">Sumar a mi equipo ↗</button></div></div>`;openLayer($('#product-modal'));const url=new URL(location.href);url.searchParams.set('producto',id);history.replaceState(null,'',url)}
function initLayers(){state.cart=readCart();renderCart();$$('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>openLayer($('#cart-drawer'))));$$('[data-close]').forEach(b=>b.addEventListener('click',closeLayers));$('#overlay').addEventListener('click',closeLayers);$('#cart-items').addEventListener('click',e=>{const b=e.target.closest('[data-remove]');if(b){state.cart=state.cart.filter(x=>x.id!==b.dataset.remove);saveCart()}if(e.target.closest('[data-cart-close]')){closeLayers();$('#catalogo').scrollIntoView()}});$('#modal-body').addEventListener('click',e=>{if(e.target.closest('#modal-add')&&state.product){addProduct(state.product.id);closeLayers()}});addEventListener('keydown',e=>{const layer=!$('#cart-drawer').hidden?$('#cart-drawer'):!$('#product-modal').hidden?$('#product-modal'):null;if(!layer)return;if(e.key==='Escape'){closeLayers();return}if(e.key==='Tab'){const focus=[...layer.querySelectorAll('button:not([disabled]),a[href],input')];if(!focus.length)return;const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});addEventListener('scroll',()=>$('.floating-actions').classList.toggle('visible',state.cart.length>0||scrollY>550),{passive:true});const id=new URL(location.href).searchParams.get('producto');if(id&&PRODUCTS.some(p=>p.id===id))openProduct(id)}
function initNav(){const b=$('.menu-toggle'),nav=$('.main-nav');b.addEventListener('click',()=>{const open=nav.classList.toggle('open');b.setAttribute('aria-expanded',String(open));b.setAttribute('aria-label',open?'Cerrar menú':'Abrir menú')});nav.addEventListener('click',e=>{if(e.target.closest('a')){nav.classList.remove('open');b.setAttribute('aria-expanded','false')}})}
function initModelBar(){const bar=$('.gw-modelos');let frame=0,timer=0;addEventListener('scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(timer);timer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)})},{passive:true})}
function initReveals(){const nodes=$$('[data-animate]');if(matchMedia('(prefers-reduced-motion: reduce)').matches){nodes.forEach(n=>n.classList.add('in'));return}const io=new IntersectionObserver(entries=>entries.forEach(e=>{if(e.isIntersecting){e.target.classList.add('in');io.unobserve(e.target)}}),{threshold:0,rootMargin:'0px 0px 80px 0px'});nodes.forEach(n=>io.observe(n))}
initCatalog();initLayers();initNav();initModelBar();initReveals();
