<?php
/**
 * wabot/consultas-ejemplos.php — cómo preguntan los clientes cada tema (2-oct-2026).
 *
 * Pablo: "agregale variantes de cada respuesta/pregunta del cliente, dale varias
 * variaciones de lo mismo, para que entienda mejor". Clave (la de `info` en
 * textos.php o la regla de postprecio.php) => formas reales de preguntarlo,
 * sacadas de las charlas del 11-sep al 2-oct (sin nombres ni montos viejos),
 * más algunas armadas a mano donde había pocas. Se le pasan a OpenAI como
 * ejemplos: wabot_ia_info_comercial() (ia.php) y el catálogo de postprecio.php.
 * Para sumar una forma nueva que no entendió, agregala en su clave.
 */
/* Formas reales en que los clientes preguntan cada tema (chats 11-sep a 2-oct-2026), para el clasificador. */
return [
    'proceso' => [
        'Si, te consulto para hacer la página, la diseñas y me la mostras? como seria esa parte?',
        'Ah, genial.. y ustedes arman todo.. como es?',
        'Y como funciona?',
        'Si me interesa como es.',
        'Y cómo hacemos?',
        'Cómo sería eso',
        'consulto por precios y como sería el procedimiento',
        'Quería averiguar precios y metodologías de trabajo',
        'Como sería si yo contrato que ustedes realicen la página?',
        'Quería saber cómo es? En la publicación decía autogestionable',
        'como es el paso a paso?',
        'q hay q hacer para arrancar?',
    ],
    'pago' => [
        'Precio y forma de pago',
        'Como sería el pago?',
        'Cómo es el método de pago?',
        'Se abona al terminar el trabajo o antes de comenzar?',
        'Cuando se paga antes o después',
        'Ok y cuando abonaria el mes?',
        'Osea lo tngo q abonar ahora?',
        'Pero ustedes me hacen recordar del pago?',
        'hay que dejar seña?',
        'se paga todo junto o una parte al principio?',
        'como se abona, transferencia?',
    ],
    'plazos' => [
        'Una vez que abone cuanto demora?',
        'Y en cuantos día estará disponible?',
        'cuánto demora aproximadamente el desarrollo completo una vez aprobado el diseño',
        'después de cuanto tiempo podré tener la página para subir cosas?',
        'cuánto tiempo duraría o cómo es que se maneja esto',
        'en cuanto tiempo la tengo lista?',
        'cuanto tardan en hacerla?',
        'para cuando estaria?',
    ],
    'hosting' => [
        'quería saber si incluye host y dominio o como hago para tenerla funcionando',
        'cómo funciona el tema del hosting?',
        'El hosting está incluido, no está incluido por mes, según la modalidad?',
        'En el pago único, ¿el dominio y hosting inicial están incluidos?',
        'puedo renovar dominio y hosting por mi cuenta o tiene que ser con ustedes?',
        'El hosting me lo prestan y ya tengo el dominio',
        'el servidor lo pago aparte?',
        'incluye hosting?',
        'donde queda alojada la pagina?',
    ],
    'mantenimiento' => [
        'Incluye mantenimiento?',
        'Mantenimiento que sería perdón?',
        'Q incluye la actualización q me decís con el abono',
        'La suscripción por mes incluye actualización?',
        'No me interesa el mantenimiento',
        'qué es lo que incluye el mantenimiento?',
        'si no contrato mantenimiento, la web puede seguir funcionando normalmente?',
        'si aparece algún error técnico, puedo pedir una reparación puntual?',
        'el mantenimiento es obligatorio?',
        'que me cubre el mantenimiento?',
    ],
    'carga' => [
        'Mí duda es los productos los cargo yo?',
        'Quien lo maneja',
        'Consulta quien manejaria las páginas',
        'la página la administras vos o nosotros?',
        'tengo algún link como de admin para actualizar o algo así?',
        'A mí me interesaría poder actualizarla yo... Es posible?',
        'Cuantas fotos podemos subir o como es?',
        'En los 3 planes yo puedo modificar stock, precio, imagen??',
        'Como haria para el control de la cuenta? Me pasan un ID?',
        'Osea ustedes se encargan de todo manejo y todo?',
        'cuánto es el adicional para cargar todos los productos con fotos y precios?',
        'cuando no hay stock se actualiza solo?',
    ],
    // Chats del 9-oct: medios de pago de la tienda y el nombre que figura al cobrar.
    'medios_pago_tienda' => [
        'ok pásame el demo y los medios de pago te los pasaría yo?',
        'qué medios de pago se pueden poner en la web?',
        'en la tienda mis clientes pueden pagar con transferencia o efectivo?',
        'puedo usar otra billetera virtual en vez de mercado pago?',
    ],
    'mp_nombre_negocio' => [
        'cuando paguen no quiero que aparezca mi nombre de la cuenta, quiero que aparezca el nombre de fantasía',
        'cuando me pagan figura mi nombre o el del negocio?',
        'se puede cobrar con el nombre de la marca y no con el mío?',
    ],
    // Que los carguemos NOSOTROS (9-oct: "Se pueden cargar todos ustedes?" recibía "lo manejás vos").
    'carga_nosotros' => [
        'Se pueden cargar todos ustedes?',
        'Los articulos los cargan ustedes o lo debo hacer yo?',
        'los productos vienen ya cargados? yo te paso los precios, los ponés vos o cómo funciona eso?',
        'Los productos los podemos llenar nosotros o los llenan ustedes?',
        'son muchos productos, me los pueden subir ustedes?',
        'ustedes me cargan todo el catálogo con fotos y precios?',
    ],
    'logo' => [
        'Si te paso el logo',
        'el logo me lo hacen ustedes?',
        'hacen logos?',
        'me pueden diseñar el logo tambien?',
        'tengo un logo viejo, lo pueden mejorar?',
        'el diseño del logo esta incluido?',
        'necesito logo, lo arman?',
    ],
    'marketing' => [
        'Trabajan con community manager?',
        'Uds lo mueven para llegar a más personas, o tengo que pagar en otro lado?',
        'hacen aparte publicidad?',
        'Tambien que manejen la publicidad ya sea instagram o google',
        'Trabajan con perfiles de instagram aparte de páginas web?',
        'Cuanto los anuncios por mes?',
        'Necesito para redes....',
        'Quiero meter propaganda en Instagram y tik tok',
        'cómo me pueden ayudar para tener seguidores, para subir la venta',
        'cómo promocionamos nosotros la página nuestra?',
    ],
    'reuniones' => [
        'Buenísimo y si se puede hacer la videollamada',
        'podemos coordinar alguna videollamada el lunes por Teams?',
        'No me mandarías el link para unirme por acá?',
        'De forma presencial quiero',
        'Podría sumarse una compañera que me ayuda con estas cosas?',
        'podemos hacer una llamada?',
        'hacemos un zoom para verlo?',
        'me podes llamar?',
    ],
    'tecnologia' => [
        'en que tecnologia trabajan?',
        'Qué tecnología/plataforma utilizan para hacerla? WordPress u otra?',
        'Y sobre Firebase: si se supera el plan gratuito, ¿cómo funcionaría?',
        'con que programa la hacen?',
        'es wordpress?',
        'en que lenguaje esta hecha?',
        'usan algun constructor tipo wix?',
    ],
    'precio_sin_rubro' => [
        'Hola! Quiero pedir presupuesto para mi web.',
        'Precio?',
        'Cuanto sale',
        'Que valor tiene',
        'Costos?',
        'Hola me das info de valor para web porfavor',
        'Que precio tiene crear una página web',
        'Info y precios gracias',
        'Quería saber cuanto me sale hacer una página web',
        'Buen día, q costo tiene una página web?',
        'Cuanto una pagina web',
        'Hola precio',
    ],
    'rangos' => [
        'Más o menos cuanto sale?',
        'Tienda on line para vender productos que precio tiene aproximadamente',
        'qué opciones ofrecen y aproximadamente qué valores manejan',
        'Necesito tener idea de costos para saber si puedo hacerlo',
        'Cuanto saldria una pagina sencilla?',
        'estoy averiguando recien pero me sirve para tener como parametro',
        'un rango de precio aprox?',
        'desde cuanto arrancan?',
    ],
    'ubicacion' => [
        'Hola buen día de donde son???',
        'De dónde son zona',
        'De donde son ustedes?',
        'Me interesa de dónde son',
        'Y pásame su ubicación xfa',
        'tienen oficina?',
        'donde estan ubicados?',
        'son de caba?',
    ],
    'accesos' => [
        'Me entregan acceso completo de administrador y todas las credenciales?',
        'Hola, no tengo acceso y tampoco me lo da',
        'Si más adelante quisiera cambiar de proveedor, otro desarrollador podría continuar?',
        'me pasan el usuario y contraseña del hosting?',
        'voy a tener acceso al servidor?',
        'puedo entrar yo al hosting?',
    ],
    'titularidad' => [
        'El hosting, dominio y mantenimiento son míos si trabajo con ustedes',
        'si yo dejo de trabajar con ustedes, me quedo con la página?',
        'quién es el propietario de todos los archivos y contenidos?',
        'El dominio, hosting y la web quedan a mi nombre?',
        'Si no se abona se pierde la página?',
        'si dejo de pagar no tengo más el lugar o no puedo publicar más?',
        'al ser pago único, quiero que toda la infraestructura quede bajo mi control',
        'la pagina es mia o de ustedes?',
    ],
    'emails' => [
        'Sabes q no puedo ingresar a mi webmail',
        'incluye mail con mi dominio?',
        'me dan un correo tipo info@minegocio?',
        'puedo tener casillas de correo?',
        'viene con email corporativo?',
        'el mail profesional esta incluido?',
    ],
    'entrega_codigo' => [
        'Pagué por toda la web y ahora no me quiere dar el código',
        'si dejo de trabajar con ustedes, me quedo con la página?',
        'me entregan acceso completo al código fuente de la web?',
        'me pasan el codigo?',
        'el codigo fuente me lo dan?',
        'me quedo con los archivos de la web?',
    ],
    'licencias' => [
        'Utilizan plugins o servicios pagos que requieran renovaciones anuales?',
        'las licencias quedan a mi nombre?',
        'los plugins se pagan aparte?',
        'hay que pagar licencias?',
        'usan algo pago que despues tenga que renovar?',
        'la plantilla tiene licencia?',
    ],
    'manual' => [
        'Ustedes me enseñan?',
        'yo no tengo idea como usarla, siempre trabaje con local físico',
        'El panel es sencillo de usar y brindan alguna capacitación?',
        'Incluyen alguna explicación o capacitación para aprender a administrar la tienda?',
        'habrá posibilidades de que más o menos me orientes?',
        'hay un tutorial?',
        'me explican como se usa?',
    ],
    'bilingue' => [
        'se puede en ingles?',
        'la web puede estar en dos idiomas?',
        'se puede traducir al portugues?',
        'tengo clientes de afuera, puede estar en otro idioma?',
        'es bilingue?',
        'puede tener boton para cambiar de idioma?',
    ],
    'ejemplos' => [
        'Enviame muestras de sitios funcionando por favor',
        'Me mandas algun ejemplos de lo que hacen?',
        'Tenes ejemplos para ver',
        'Tenés algún ejemplo para ver?',
        'Tenes alguno que hayas realizado a farmacia',
        'estaba mirando.. no tenes ninguna de mi rubro..',
        'hay algun video de como es la pagina?',
        'Tendria para mostrarme alguna pagina para ver?',
        'yo pensé que tenías algún modelo para mostrarme cómo funcionaba',
        'Con ver alguna captura de alguno de sus trabajos me alcanza',
    ],
    'migracion' => [
        'Ya tenemos una página desarrollada',
        'Podemos pasar todo y que uds la hagan',
        'Osea migrar lo que ya vendo x ML',
        'Lo pasan a mi sitio web?',
        'Lo q queremos hacer es la misma página sacando algunos puntos',
        'tenemos una pagina pero no es atractiva no es practica',
        'pasan las cosas de mi web vieja?',
    ],
    'formularios' => [
        'incluyen una seccion para envio de mail para que consulten los clientes?',
        'formulario y eso no voy a querer',
        'puede tener formulario de contacto?',
        'se puede poner un form para que me dejen sus datos?',
        'las consultas me llegan al mail?',
        'se pueden hacer encuestas?',
    ],
    'imagenes_web' => [
        'Te tengo que pasar info? Fotos?',
        'Pero las fotos las paso yo? O vos las elegis desde mi instagram?',
        'Aun no tengo fotos pero vi su publicidad y por eso pregunto.',
        'la web lleva fotos?',
        'ponen imagenes ustedes?',
        'si no tengo fotos q ponen?',
    ],
    'inscripcion' => [
        'Hace falta vender en blanco, porque yo recién arranco',
        'Ya tengo patentada la marca ahora quiero hacer la página soy monotributista',
        'tengo que ser monotributista?',
        'necesito estar inscripto en arca?',
        'hace falta tener cuit?',
        'puedo vender sin estar en blanco?',
    ],
    'comparando' => [
        'tengo un par de presupuestos mas',
        'Estuve mirando varias ofertas y ahora me centré más en la de ustedes',
        'estoy averiguando recien pero me sirve para tener como parametro',
        'estoy esperando varios presupuestos',
        'estoy comparando con otras agencias',
        'otro me cobra menos, que tienen ustedes de diferente?',
    ],
    'ya_tiene_plataforma' => [
        'Ya tengo una web que no funciona. Hay que mejorarla o hacer otra',
        'tengo una página web ya hecha en Hostinger, ustedes hacen mantención?',
        'La página está hecha en WordPress',
        'Tengo mi página web con dominio a mi nombre, pero mi programador no la está renovando',
        'Mi sobrina armó una página pero queremos optimizarla',
        'necesito optimización de la misma',
        'Yo vendo x mercado libre',
    ],
    'no_se_nada' => [
        'no entiendo mucho del tema nunca he tenido tienda online',
        'yo no tengo idea, siempre trabaje con local físico',
        'Nosé mucho de esto.',
        'voy a decirle que lea el formulario y me asesore porque yo no tengo ni idea',
        'Yo vendo calzados..pero cero con las redes',
        'no se nada de paginas web',
        'soy medio nula con la tecnologia',
    ],
    'sin_logo' => [
        'no tengo logo',
        'todavia no tengo logo, igual se puede?',
        'sin logo se puede hacer?',
        'logo no tengo aun',
        'no tengo marca armada todavia',
        'el logo lo estoy haciendo, puedo arrancar igual?',
    ],
    'sin_fotos' => [
        'Aun no tengo fotos',
        'La semana entrante les paso las fotos porque ahora no tengo ninguna',
        'estoy armando las fotos, va a tomar unos días más',
        'no tengo fotos buenas',
        'fotos no tengo, igual se puede?',
        'las fotos las saco despues',
    ],
    'muestra_no_es_final' => [
        'lo que yo le dije que me parece que es porque solo es un demo, y luego hay que ampliar',
        'no llego a ver bien el diseño de cómo quedó',
        'asi va a quedar la web?',
        'esta es la pagina final?',
        'la demo es la web terminada?',
        'despues se le agrega lo que falta?',
    ],
    'responsive' => [
        'Página para kiosko chiquito que funcione desde el celular y la computadora',
        'Necesito una página. Para celular',
        'veo todo como agrandado en el celular',
        'se ve bien en el celu?',
        'se adapta al telefono?',
        'funciona en tablet?',
    ],
    'seguridad' => [
        'La web incluye copias de seguridad/backups?',
        'es segura la pagina?',
        'tiene certificado ssl?',
        'la pueden hackear?',
        'tiene https?',
        'los datos de los clientes estan protegidos?',
    ],
    'google' => [
        'está web aparece en Google o en dónde?',
        'configuración básica para aparecer en Google?',
        'voy a salir en google?',
        'me encuentran en google?',
        'hacen seo?',
        'aparezco primero en google?',
    ],
    'maps' => [
        'Incluye botón directo a WhatsApp, ubicación, horarios y mapa?',
        'Incluye integración con Google Maps?',
        'se puede poner el mapa del local?',
        'puede tener la ubicacion con google maps?',
        'que me encuentren con el gps?',
        'ponen como llegar?',
    ],
    'ampliar_despues' => [
        'A medida que yo avance con este proyecto y quiera agregar algo que costo tiene?',
        'Está preparada para después agregar nuevas funciones si el negocio crece?',
        'Sumaria el resto más adelante, la idea es la tienda primero',
        'mi idea es empezar con lo que tengo. Y luego agregar',
        'Es para vender insumos y mas adelante cargar cursos online tambien',
        'lo de las redes seguro sea más adelante cuando tenga más armado',
    ],
    'que_necesitan' => [
        'no se que datos mas necesitas',
        'Que necesitas para realizar el diseño de prueba',
        'Si que necesitas para hacerlo',
        'que datos necesitas te paso',
        'Que info estimada tendria que pasarte?',
        'Q necesitan',
        'Qué requisitos tengo que mandarte',
        'que requisitos tengo que tener para que puedas crear',
        'Yo tngo q pasarte foto de mis productos medidas precio',
        'Te tengo que pasar info? Fotos?',
        'decime que necesitas para darnos de alta',
        'Alguna información más a tener en cuenta antes de avanzar?',
    ],
    'soy_bot' => [
        'sos un bot?',
        'estoy hablando con una persona?',
        'es un contestador automatico?',
        'sos humano?',
        'me responde una maquina?',
        'esto es automatico?',
    ],
    'quien_atiende' => [
        'Su nombre?',
        'me decis tu nombre?',
        'Tu nombre es?',
        'No sé con quién hablo',
        'con quien hablo?',
        'quien me atiende?',
    ],
    'exclusividad' => [
        'Es una plantilla que ustedes usan para todos los clientes o es personalizado?',
        'mi web va a ser igual a otra?',
        'es un diseño exclusivo?',
        'usan la misma plantilla para todos?',
        'no va a haber otra igual no?',
        'es a medida o plantilla?',
    ],
    'fotos_propiedad' => [
        'cuantas fotos puedo subir por propiedad?',
        'se puede subir video de la casa?',
        'las propiedades pueden tener muchas fotos?',
        'hay limite de fotos por inmueble?',
        'puedo poner un recorrido en video?',
        'cuantas imagenes por depto?',
    ],
    'impuestos_importacion' => [
        'calcula los impuestos de importacion?',
        'vendo productos de afuera, suma la aduana?',
        'se puede sumar el costo de aduana?',
        'la tienda calcula impuestos?',
        'traigo de china, calcula tasas?',
        'agrega el iva y la aduana sola?',
    ],
    'demo_vigencia' => [
        'hasta cuando puedo ver la demo?',
        'la demo se borra?',
        'cuantos dias queda la muestra?',
        'no la pude ver, sigue online?',
        'la puedo mirar la semana que viene?',
        'por que se vence la demo?',
    ],
    'facturacion' => [
        'Que tipo de facturación hacen',
        'Cuando puedas mándame la factura c',
        'hacen factura?',
        'me podes hacer factura a?',
        'emiten factura con iva?',
        'me das factura?',
    ],
    'apps' => [
        'no estoy buscando una página sino más bien una app',
        'Estoy buscando desarrollar una app solamente',
        'Es una aplicación. Sobre turismo',
        'hacen aplicaciones para celular?',
        'me pueden hacer una app?',
        'cuanto sale una app?',
    ],
    'las_dos_formas' => [
        'Y se puede agregar enlace de WhatsApp además?',
        'Estaria bueno las dos cosas que puedan comprar desde la pagina y ver los productos',
        'En lo posible vender y de última terminar por wpp',
        'Se puede incluir el botón. Para Whatsapp no?',
        'puede tener carrito y whatsapp?',
        'que compren online o me escriban, las dos?',
    ],
    'que_es_landing' => [
        'No sé si sea landing page o ya sería otra cosa',
        'Y la landing?',
        'también hacen Landing Page?',
        'que es una landing?',
        'landing es una sola pagina?',
        'que diferencia hay entre landing y web?',
    ],
    'contacto_desarrollador' => [
        'Buenas nadie se comunicó por whatsapp',
        'Por dónde la enviaron?',
        'Podré hablar con una persona?',
        'quisiera hablar con alguien',
        'como me comunico con el desarrollador?',
        'me escribe el o le escribo yo?',
        'cual es el numero del programador?',
    ],
    'sin_whatsapp' => [
        'Se puede incluir el botón. Para Whatsapp no?',
        'no uso whatsapp',
        'no quiero poner mi whatsapp',
        'no tengo whatsapp business',
        'prefiero que me escriban por mail',
        'sin whatsapp se puede?',
        'que me contacten por formulario mejor',
    ],
    'comisiones' => [
        'si ustedes cobran comisión por venta',
        'con el pago único, ustedes no cobran ninguna comisión por cada venta, verdad?',
        'Las únicas comisiones serían las propias de Mercado Pago/tarjetas?',
        'cobran porcentaje de las ventas?',
        'se quedan con algo de cada venta?',
        'hay comision?',
    ],
    'envios' => [
        'Y los envios internacionales como se integran?',
        'les suma el envío x correo argentino, como se hace eso',
        'Cuál es mejor, nunca trabaje con envios',
        'Se puede vincular con correo argentino?',
        'Se pueden configurar formas de envío, retiro en el local y opciones según la zona?',
        'envíos por zona, a todo el país y opción a coordinar',
        'La segunda opción es poniendo código postal y ya te da el precio?',
        'vos tenés que hacer los envíos, todo eso?',
        'calcula el envio?',
        'trabaja con andreani?',
    ],
    'como_funciona_tienda' => [
        'Ok tiene el carrito de compras',
        'Comprar sería con el carrito de compras no?',
        'quería saber si se puede realizar para vender por la página',
        'la gente q compra lo abona directamente de la página o se contactan conmigo?',
        'La web sería solo catálogo o también tienda con carrito y compra directa?',
        'La tienda quedaría lista para vender de forma completa desde la web?',
        'Quiero promocionar los productos y si se puede vender por la web también',
        'Y eso lo vendo a través de mis redes?',
        'comparto la página de mercado libre y me piden por privado, sería igual?',
    ],
    'que_incluye' => [
        'Que incluye',
        'Se paga algo aparte o solo los valores que me pasaste?',
        'por mes incluyen todo, es asi?',
        'ese sería el precio final por mes?',
        'Hay algún costo futuro obligatorio además del dominio y hosting?',
        'ustedes me hacen el dominio, todo completo?',
        'Uds arman la pagina y yo tengo un costo mensual?',
        'Cuantos productos incluye?',
    ],
    'emprendimientos' => [
        'yo recién me estoy iniciando, me sirve igual hacerlo??',
        'Aún ningún negocio. Quiero ver con que arrancar',
        'Podría arrancar solo con figuras de yeso',
        'quiero empezar a emprender sin negocio físico',
        'hasta ahora son 10, quiero hacer poquitos es para probar',
        'Necesitamos algo simple y económico',
        'es un emprendimiento chico, sirve igual?',
    ],
    'que_hacemos' => [
        'Hola info porfavor',
        'Buenas tardes uds preparan páginas de ebooks?',
        'Necesito saber si ustedes hacen páginas para vender cursos',
        'también hacen Landing Page?',
        'Quería consultar qué tipos de páginas realizan',
        'Hola!! Me pasarían información',
        'Hla, una página para vender fotos????',
        'quería saber el costo de la creación de una página en instagram',
    ],
    'internet' => [
        'Se puede hacer sin internet?',
        'funciona sin conexion?',
        'si se corta el wifi anda?',
        'necesito internet para usarla?',
        'el panel anda offline?',
        'se puede usar sin datos?',
    ],
    'pixel' => [
        'se puede poner el pixel de meta?',
        'conectan google analytics?',
        'puedo medir las visitas?',
        'tiene para poner el pixel de facebook?',
        'sirve para hacer campañas con pixel?',
        'se puede vincular con tag manager?',
    ],
    'confianza' => [
        'Es legal esto no?',
        'no voy a pagar algo que por ahí después no me gusta',
        'si hay garantía para corregir errores después de publicar',
        'como se que no es una estafa?',
        'son confiables?',
        'tienen referencias?',
    ],
    'dominio_com' => [
        'Para el dominio www. Es mucho más caro?',
        'puede ser .com en vez de .com.ar?',
        'quiero que termine en .com',
        'el .com sale mas?',
        'se puede .com sin el ar?',
        'cuanto sale el punto com?',
    ],
    'cupones' => [
        'cupones y secciones de temporada editables',
        'Se pueden destacar promociones, ofertas y productos destacados?',
        'puedo hacer descuentos?',
        'se pueden crear cupones?',
        'puedo poner un codigo de descuento?',
        'se puede hacer promo 2x1?',
    ],
    'cobros_tienda' => [
        'Como se agregan los medios de pagos?',
        'Mi medio de cobro es mercadopago?',
        'los redireccionaria para pagar automáticamente por mercado pago?',
        'incluye medios de pago como Mercado Pago?',
        'Mercado Pago vinculado directamente a mi cuenta?',
        'Esto incluye venta en moneda extranjera?',
        'Me gustaria vender y cobrar online x la pagina',
        'transferencia y efectivo al retirar',
    ],
    'turnos' => [
        'como es el tema de las reservas online?',
        'Ok gracias. Buscaba un sistema con reservas online',
        'calendario con reservas online, que los clientes vean disponibilidad',
        'Solo consulta por wp? No hay reservas online',
        'que los turnos vayan al whatsapp',
        'Escribirme y pedirme un turno',
        'se pueden sacar turnos desde la web?',
    ],
    'usuarios' => [
        'los clientes se pueden registrar?',
        'puede tener login para clientes?',
        'que cada cliente tenga su cuenta?',
        'se pueden crear usuarios?',
        'mis alumnos entran con usuario y clave?',
        'un area privada para socios se puede?',
    ],
    'estadisticas' => [
        'hay alguna forma de poder ver los leads que llegan?',
        'puedo ver cuanta gente entra?',
        'tiene estadisticas?',
        'veo cuanto vendo en el panel?',
        'se puede saber de donde vienen las visitas?',
        'tiene metricas?',
    ],
    'baja_del_plan' => [
        'hay un tiempo minimo?',
        '¿puedo entonces cancelar y ya está?',
        'yo no estoy en ninguna suscripción, ¿verdad?',
        'Si no se abona se pierde la página?',
        'como doy de baja la suscripcion?',
        'si quiero cancelar el mensual?',
        'hay permanencia?',
    ],
    'cuenta_mercado_pago' => [
        'necesito cuenta de mercado pago para pagar?',
        'no tengo mercado pago, puedo pagar igual?',
        'me tengo que hacer cuenta en mp?',
        'puedo pagar la suscripcion con tarjeta sin mp?',
        'sin cuenta de mercadopago se puede?',
        'mp no uso, hay otra forma?',
    ],
    'plan_es_servicio' => [
        'No me interesa el mantenimiento. No creo que sea necesario mensualmente',
        'No creo que requiera ni un cambio por mes',
        'no sabía que requería un abono mensual pensé q era el diseño',
        'Tengo que pagar eso por mes?',
        'no quiero pagar todos los meses',
        'por que tengo que pagar mensual si ya esta hecha?',
        'lo mensual es obligatorio?',
    ],
    'un_solo_pago' => [
        'Y si quisiera hacerlo en un solo pago?',
        'si en algún momento quiero pagar la totalidad, se descuentan los meses?',
        'se puede pagar todo de una?',
        'prefiero pagar una sola vez',
        'hay opcion de pago anual?',
        'puedo pagar el año entero?',
    ],
    'web_propia' => [
        'Y si quisiera hacerlo en un solo pago para la creación y encargarme yo de mantenerla?',
        'mi idea es hacer una inversión ahora y administrar la web yo misma sin un plan mensual',
        'Mi idea sería que quede dominio mío + hosting mío + ustedes como desarrolladores',
        'quiero pagarla y que sea mia',
        'quiero comprar la web, no alquilarla',
        'pago una vez y me la quedo?',
    ],
    'mensual' => [
        'Que sería el pago mensual?',
        'Tengo que pagar eso por mes?',
        'el pago es única vez o es mensual?',
        'Todos los meses debo abonar eso?',
        'Me comentas como es el tema de la suscripción?',
        'Cada cuanto aumentan los pagos mensuales o es fijo durante un año?',
        'Cuánto dura la suscripción?',
        'mientras dure la suscripción y cuanto dura??',
        'Como es el tema de la suscripcion?',
        'una vez que se cumple el año? Se vuelve a pagar?',
        'si pago mensualmente usted me armaria la tienda online?',
        'Cuál es el costo por mes?',
    ],
    'cuotas' => [
        'Cuánto sería el pago único en cuotas',
        'Porque trabajo solo en efectivo o transferencia',
        'se puede en cuotas?',
        'aceptan tarjeta de credito?',
        'puedo pagar con tarjeta?',
        'hay cuotas sin interes?',
        'lo puedo pagar en 3 cuotas?',
        'el anual se puede en cuotas?',
    ],
    'dominio_a_nombre' => [
        'Pero me gustaría tener el dominio a nombre mío',
        'El dominio puede quedar registrado directamente a mi nombre?',
        'que pasa si el dominio queda registrado a nombre de la Iglesia?',
        'en qué momento se hace la transferencia a mi nombre y si tiene costo',
        'Eso pago por el dominio, ya lo tengo',
        'Y el nombre de la página lo ponen uds o tengo que comprarlo yo?',
        'el dominio queda a mi nombre?',
    ],
    'que_es_dominio' => [
        'qué significa dominio de la web? Que no entiendo.',
        'Cuál es el dominio de la página web',
        'cómo seria la dirección url?',
        'Desde donde ingresarian para ver la pagina?',
        'ustedes esto lo suben en algún lugar y lo puedo reenviar por WhatsApp?',
        'que es el dominio?',
        'cual seria el link de mi pagina?',
        'como la encuentran en internet?',
    ],
    'que_es_hosting' => [
        'el tema del mantenimiento por mes, renovación de hosting y dominio, perdón por la ignorancia, pero nunca tuve, no sé qué vendría a ser eso',
        'qué es el hosting?',
        'que significa hosting y dominio?',
        'no entiendo eso del hosting',
    ],
    'demo_gratis' => [
        'La prueba tiene costo?',
        'Esto es solo presupuesto no? No tengo q abonar nada, solo llenar los datos',
        'Si es sin cargo si',
        'Sisi es sin compromiso si',
        'no voy a pagar algo que por ahí después no me gusta',
        'la muestra se paga?',
        'tengo que pagar algo para ver el diseño?',
        'es gratis la demo?',
    ],
    'alternativas' => [
        'entonces es o una opción o la otra? Una es mensual y la otra Anual!?',
        'tengo que abonar el pago único y luego elegir el plan anual o mensual?',
        'sería el pago único y luego por mes mientras yo decida mantener la página?',
        'Este era para plan mensual?',
        'se suman los dos?',
        'pago el unico y aparte el mensual?',
        'es uno u otro?',
    ],
    'plataformas' => [
        'trabajan tienda nube?',
        'tienda nube haces?',
        'Es tienda nube?',
        'Esto sería en tiendanube o algo así o me equivoco?',
        'esto es lo que llaman una tienda nube?',
        'Tipo una tienda nube necesito',
        'preferiría un tipo tienda nube, como para q hagan pedidos',
        'hacer otra con tienda nube (supongo que es mas economico)',
        'Qué plataforma utilizan? WordPress u otra?',
        'me arman en wordpress',
        'es shopify?',
    ],
    'recomendar_plan' => [
        'Que me recomendas?',
        'Pero cual es el que me conviene?',
        'si ven que hay una mejor opción de lo que elegi se los dejo a ustedes',
        'Que diferencia hay entre el plan anual con mantenimiento y el de pago único.',
        'cual me sale mas a cuenta?',
        'vos cual elegirias?',
        'que plan me conviene para arrancar?',
    ],
    'precio' => [
        'Me recordas los valores porfa',
        'Cuanto era el precio?',
        'valores por favor',
        'Cual es el costo?',
        'Y cuantos me sale?',
        'Hola quisiera saber cual es el valor total',
        'Perfecto, que sale hacer la web?',
        'Los valores necesito bien explicado',
        'Valor total?',
    ],
    'pago_link' => [
        'Mándame los datos de mercado pago',
        'pásame los datos así puedo transferir lo de este mes',
        'te paso a vos por aca o en el link',
        'esta bien? es tu cuenta?',
        'estoy por hacer la transferencia',
        'podemos avanzar con el plan anual',
        'Nos suscribimos con la opción 2. Mensual',
        'pasame el link para pagar',
        'a donde te transfiero?',
    ],
    'detalle_modalidades' => [
        'Los valores necesito bien explicado',
        'Me comentas como es el tema de la suscripción?',
        'Que diferencia hay entre el plan anual y el de pago único.',
        'me pasas el detalle de cada plan?',
        'donde veo que incluye cada opcion?',
        'tenes una pagina con los planes?',
        'me explicas bien las 3 opciones?',
    ],
    'demo_aceptar' => [
        'Dale si',
        'Si por favor',
        'Quiero una demo',
        'Me gustaría que me hagan el demo',
        'Dale si me interesa',
        'Sisi es sin compromiso si',
        'Si te paso el logo',
        'Se puede ver cómo quedaría?',
        'Ok si no es molestia me lo prepararías para ver como quedaria',
        'Podria ser... quiero ver como quedaria',
        'Dale si me interesa un primer diseño para ver como seria',
        'Ok dale. Mostrame x favor',
        'Buenoo a ver cómo quedaría',
        'Si es sin cargo si',
        'Bueno dale',
    ],
    'form_estado' => [
        'Ya llene el formulario',
        'Ya completé el formulario.',
        'Genial, ahí complete para el demo.',
        'listo ya complete',
        'Completado, muchas gracias!!',
        'te llego el formulario?',
        'lo complete, lo recibiste?',
    ],
    'demo_plazo' => [
        'Ya la enviaron?',
        'Por dónde la enviaron?',
        'Buenas nadie se comunicó por whatsapp',
        'quería saber si tenés disponible el diseño de ejemplo',
        'cuando me llega la demo?',
        'para cuando estaria la muestra?',
        'en cuanto tiempo me la mandan?',
    ],
    'modelo' => [
        'El modelo dos lo veo más facil',
        'Hola, me gustó mucho el modelo 1.',
        'Buenas, recién las vi el modelo dos me pareció mas atractivo',
        'El primero',
        'Gracias la verdad me gustó el primero.',
        'Me interesa el modelo 2',
        'El 1',
        'Me gustó más el modelo 2',
    ],
    'cambios' => [
        'hay que cambiar varias cosas del demo',
        'hay textos de la demo que hay que cambiar',
        'Te voy pasando unos puntos a modificar',
        'Agregar una sección de experiencia',
        'Más colores en el fondo me gustaria',
        'Se pueden elegir otros colores en naranja',
        'cambiarle un poco lo minimalista y usar colores negro y dorado',
        'Quisiera que diga ropa de diseño, elegante, audaz y urbana',
        'El horario de atención lo sacamos',
        'Si cambiaría detalles.',
    ],
    'demo_limites' => [
        'no veo que funcione lo de las compras',
        'le gustaria que cada pestaña te lleve a una galeria, link o whatsapp',
        'no llego a ver bien el diseño de cómo quedó',
        'no anda el carrito',
        'los botones no hacen nada',
        'no puedo comprar en la demo',
    ],
    'postergar' => [
        'Ok gracias después te aviso',
        'Te confirmo en la semana q pueda juntar el dinero',
        'voy a esperar al mes que viene para arrancar',
        'Lo converso con mi equipo primero',
        'Lo consulto y te aviso',
        'Si me interesa pero ahora no tengo nada para abonar',
        'Arranco el mes que viene',
        'Lo consulto con mi bolsillo y te aviso',
        'Dejame que vea las 3 opciones y lo decidamos con mi esposa',
        'Lo charlo con mi pareja y te vuelvo a escribir',
        'Mañana hablamos.',
        'dame tiempo hasta la proxima semana',
    ],
    'portfolio' => [
        'Enviame muestras de sitios funcionando por favor',
        'Tenes ejemplos para ver',
        'Me mandas algun ejemplos de lo que hacen?',
        'Tendria para mostrarme alguna pagina para ver?',
        'Tenes alguno que hayas realizado a farmacia',
        'no tenes ninguna de mi rubro..',
        'donde veo sus trabajos?',
    ],
    'instagram' => [
        'Tenes Instagram',
        'Tienen INSTAGRAM?',
        'como es su ig?',
        'tienen redes?',
        'los sigo en instagram?',
        'pasame el ig de ustedes',
    ],
    'identidad' => [
        'Su nombre?',
        'me decis tu nombre?',
        'Tu nombre es?',
        'No sé con quién hablo',
        'sos el dueño?',
        'sos el que hace la web?',
        'hablo con un bot?',
    ],
];
