<?php
// Las cuatro respuestas de precio del 15/16-sep, tal cual venían de fábrica: el
// archivo del server que migra test-respuestas-rapidas.php.
return [
            "Lo mejor para tu negocio es un sitio profesional donde puedas mostrar tus servicios, trabajos e información de contacto, pensado para transmitir confianza y recibir consultas.\n\nTenés dos opciones para contratar el servicio, y elegís la que más te convenga. Son alternativas, no se abonan las dos:\n\n1. Pago único de $180.000: abonás el desarrollo una sola vez e incluye mantenimiento durante el primer año.\n\n2. Suscripción mensual de $15.000: en lugar del pago único, abonás mes a mes y tenés todo incluido mientras mantengas activa la suscripción.",
            "Lo mejor para tu negocio es una web para vender online, con catálogo, carrito, integración de cobros con Mercado Pago y un panel administrativo para cargar productos y gestionar pedidos.\n\nTenés dos opciones para contratar el servicio, y elegís la que más te convenga. Son alternativas, no se abonan las dos:\n\n1. Pago único de $290.000: abonás el desarrollo una sola vez e incluye mantenimiento durante el primer año.\n\n2. Suscripción mensual de $25.000: en lugar del pago único, abonás mes a mes y tenés todo incluido mientras mantengas activa la suscripción.",
            "Lo mejor para tu inmobiliaria es una web para publicar propiedades con fotos y fichas completas, buscador por zona, tipo y precio, y un panel administrativo para cargar, editar y dar de baja propiedades.\n\nTenés dos opciones para contratar el servicio, y elegís la que más te convenga. Son alternativas, no se abonan las dos:\n\n1. Pago único de $240.000: abonás el desarrollo una sola vez e incluye mantenimiento durante el primer año.\n\n2. Suscripción mensual de $25.000: en lugar del pago único, abonás mes a mes y tenés todo incluido mientras mantengas activa la suscripción.",
            "Lo mejor para tus cursos es una plataforma con los videos subidos, acceso propio para cada alumno y cobro online.\n\nTenés dos opciones para contratar el servicio, y elegís la que más te convenga. Son alternativas, no se abonan las dos:\n\n1. Pago único de $290.000: abonás el desarrollo una sola vez e incluye mantenimiento durante el primer año.\n\n2. Suscripción mensual de $25.000: en lugar del pago único, abonás mes a mes y tenés todo incluido mientras mantengas activa la suscripción.",
];
