'use strict';

const COURSE_IMAGES = {
  formacion: 'images/05_ayurveda_sivapriya_formacion_online.jpg',
  alimentacion: 'images/04_ayurveda_sivapriya_alimentacion.jpg',
  descanso: 'images/06_ayurveda_sivapriya_calma_y_bienestar.jpg',
  introduccion: 'images/03_ayurveda_sivapriya_hierbas_y_especias.jpg'
};
const COURSES = [
  {id:'formacion',title:'Formación ayurvédica',type:'Formación',summary:'Un recorrido para conocer los fundamentos del Ayurveda y llevarlos a la vida cotidiana.',description:'Una propuesta de formación para acercarte a la mirada ayurvédica sobre hábitos, alimentación y bienestar. El programa definitivo y la modalidad se confirmarán con Fernanda.',modules:[['Fundamentos','Qué es Ayurveda y cómo se piensa el bienestar.'],['Observación cotidiana','Alimentación, rutinas y descanso.'],['Práctica personal','Cómo integrar lo aprendido con criterio y cuidado.']]},
  {id:'alimentacion',title:'Alimentación desde Ayurveda',type:'Taller',summary:'Una invitación a observar la comida, los horarios y los hábitos con mayor atención.',description:'Un taller introductorio para conversar sobre alimentación desde la tradición ayurvédica, sin recetas universales ni planes de alimentación clínicos.',modules:[['Punto de partida','Alimentación y contexto personal.'],['Hábitos','Ritmos, horarios y observación.'],['Práctica cotidiana','Preguntas para llevar a la mesa.']]},
  {id:'descanso',title:'Rutinas, calma y descanso',type:'Taller',summary:'Ideas para acompañar el descanso y hacer espacio a pausas posibles en el día.',description:'Una propuesta para explorar hábitos de descanso, pausas y bienestar cotidiano. No reemplaza la atención profesional ante ansiedad u otros síntomas.',modules:[['Ritmos cotidianos','Observar el propio día.'],['Pausas posibles','Rutinas de bienestar adaptables.'],['Continuidad','Cómo sostener pequeños cambios.']]},
  {id:'introduccion',title:'Primer encuentro con Ayurveda',type:'Charla',summary:'Una puerta de entrada a sus ideas sobre estilo de vida, alimentación y autocuidado.',description:'Una charla para conocer los conceptos iniciales del Ayurveda y descubrir qué temas te gustaría profundizar.',modules:[['Origen y mirada','Una introducción a la tradición ayurvédica.'],['Vida cotidiana','Alimentación, movimiento y descanso.'],['Preguntas abiertas','Cómo seguir explorando con criterio.']]}
];
const CART_KEY = 'ayurvedasivapriya_cart';
const $ = s => document.querySelector(s);
const $$ = s => [...document.querySelectorAll(s)];
const esc = value => String(value ?? '').replace(/[&<>"']/g, char => ({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[char]));
const normalize = value => String(value ?? '').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();
let cart = [];
try {const saved=JSON.parse(localStorage.getItem(CART_KEY)||'[]');if(Array.isArray(saved))cart=[...new Set(saved.filter(id=>COURSES.some(course=>course.id===id)))];}catch{}
let filter = '';
let query = '';
let previousFocus = null;
let toastTimer = 0;

function showToast(message){const toast=$('#toast');toast.textContent=message;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),3500);}
function saveCart(){try{localStorage.setItem(CART_KEY,JSON.stringify(cart));}catch{}updateCart();}
function updateCart(){ $$('[data-cart-count]').forEach(el=>el.textContent=cart.length);const box=$('#cart-items');if(!box)return;box.innerHTML=cart.length?cart.map(id=>{const course=COURSES.find(item=>item.id===id);return `<div class="drawer-line"><img src="${COURSE_IMAGES[id]}" alt=""><div><strong>${esc(course.title)}</strong><small>${esc(course.type)} · arancel a confirmar</small></div><button type="button" data-remove="${id}" aria-label="Quitar ${esc(course.title)}">×</button></div>`;}).join(''):'<div class="drawer-empty"><h3>Tu selección está vacía.</h3><p>Explorá las propuestas y elegí la que más te interese.</p></div>';$('.float-stack').classList.toggle('shown',scrollY>600||cart.length>0);}
function addCourse(id,open=false){if(!COURSES.some(course=>course.id===id))return;if(!cart.includes(id)){cart.push(id);saveCart();showToast('Propuesta agregada a tu selección.');}else showToast('Esta propuesta ya está en tu selección.');if(open)openLayer($('#cart-drawer'));}
function removeCourse(id){cart=cart.filter(item=>item!==id);saveCart();}
function card(course){return `<article class="course-card" data-animate="subir" style="opacity:0;transform:translateY(36px)"><div class="card-media"><img src="${COURSE_IMAGES[course.id]}" width="1200" height="1200" alt="Imagen ilustrativa de ${esc(course.title.toLowerCase())}"></div><div class="card-copy"><span class="card-type">${esc(course.type)}</span><h3>${esc(course.title)}</h3><p>${esc(course.summary)}</p><div class="card-bottom"><button type="button" data-detail="${course.id}">Ver programa ↗</button><button class="card-add" type="button" data-add="${course.id}">Sumar +</button></div></div></article>`;}
function renderCourses(){const matches=COURSES.filter(course=>(!filter||course.type===filter)&&normalize(course.title+' '+course.type+' '+course.summary+' '+course.description).includes(normalize(query)));const grid=$('#course-grid');grid.innerHTML=matches.length?matches.map(card).join(''):'<div class="empty-state"><p>No encontramos propuestas con esa búsqueda.</p><button type="button" data-clear>Ver todas</button></div>';$('#course-count').textContent=`${matches.length} ${matches.length===1?'propuesta':'propuestas'} para explorar`;revealNew(grid);}
function clearFilters(){filter='';query='';$('#course-search').value='';$$('[data-filter]').forEach(button=>button.classList.toggle('active',button.dataset.filter===''));renderCourses();}
function openLayer(layer){closeLayers(false);previousFocus=document.activeElement;$('#overlay').hidden=false;layer.hidden=false;document.body.classList.add('no-scroll');layer.querySelector('button')?.focus();}
function closeLayers(restore=true){const had=!$('#overlay').hidden;$('#course-modal').hidden=true;$('#cart-drawer').hidden=true;$('#overlay').hidden=true;document.body.classList.remove('no-scroll');if(restore&&had)previousFocus?.focus();}
function showCourse(id){const course=COURSES.find(item=>item.id===id);if(!course)return;$('#modal-content').innerHTML=`<div class="modal-grid"><div class="modal-photo"><img src="${COURSE_IMAGES[id]}" alt="Imagen ilustrativa de ${esc(course.title.toLowerCase())}"></div><div class="modal-copy"><p class="overline">${esc(course.type)} · AYURVEDA SIVAPRIYA</p><h2>${esc(course.title)}</h2><p>${esc(course.description)}</p><div class="modal-program"><h3>Temas del programa</h3>${course.modules.map(([title,body],index)=>`<details ${index===0?'open':''}><summary>${esc(title)}</summary><p>${esc(body)}</p></details>`).join('')}</div><p>Guiado por Fernanda Tilli, terapeuta ayurvédica. Modalidad, fechas, duración y arancel a confirmar.</p><button class="button button-primary" type="button" data-enroll="${id}">Sumar a mi inscripción ↗</button><p class="modal-note">Los contenidos son ilustrativos de esta demo y deben validarse con Fernanda.</p></div></div>`;openLayer($('#course-modal'));}

const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let revealObserver;
function revealNew(root=document){const items=[...root.querySelectorAll('[data-animate]:not(.in)')];if(reduceMotion||!('IntersectionObserver' in window)){items.forEach(el=>el.classList.add('in'));return;}if(!revealObserver){revealObserver=new IntersectionObserver(entries=>{let n=0;for(const entry of entries){if(!entry.isIntersecting)continue;const el=entry.target;el.style.transitionDelay=`${Math.min(n++*.1,.6)}s`;el.classList.add('in');revealObserver.unobserve(el);setTimeout(()=>el.style.transitionDelay='',1400);}}, {threshold:0,rootMargin:'0px 0px -7% 0px'});}items.forEach(el=>revealObserver.observe(el));const sweep=()=>items.forEach(el=>{if(el.classList.contains('in'))return;const rect=el.getBoundingClientRect();if(rect.top<innerHeight*.94&&rect.bottom>0){el.classList.add('in');revealObserver.unobserve(el);}});requestAnimationFrame(sweep);addEventListener('load',sweep,{once:true});}
function initModelBarScroll(){const bar=$('.gw-modelos');if(!bar)return;let timer=0,frame=0;addEventListener('scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return;}bar.classList.add('gw-modelos--scrolling');clearTimeout(timer);timer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120);});},{passive:true});}
function closeMenu(){const nav=$('#main-nav');nav.classList.remove('open');$('.menu-toggle').setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll');}

document.addEventListener('click',event=>{const detail=event.target.closest('[data-detail]');if(detail){showCourse(detail.dataset.detail);return;}const add=event.target.closest('[data-add]');if(add){addCourse(add.dataset.add);return;}const enroll=event.target.closest('[data-enroll]');if(enroll){addCourse(enroll.dataset.enroll,true);return;}const remove=event.target.closest('[data-remove]');if(remove){removeCourse(remove.dataset.remove);return;}if(event.target.closest('[data-cart-open]')){openLayer($('#cart-drawer'));return;}if(event.target.closest('[data-close]')||event.target.id==='overlay'){closeLayers();return;}if(event.target.closest('[data-clear]')){clearFilters();return;}const tab=event.target.closest('[data-filter]');if(tab){filter=tab.dataset.filter;$$('[data-filter]').forEach(button=>button.classList.toggle('active',button===tab));renderCourses();return;}if(event.target.closest('.main-nav a'))closeMenu();});
document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!$('#overlay').hidden)closeLayers();else closeMenu();return;}if(event.key!=='Tab')return;const layer=!$('#course-modal').hidden?$('#course-modal'):!$('#cart-drawer').hidden?$('#cart-drawer'):null;if(!layer)return;const focusable=[...layer.querySelectorAll('button,a,input,summary')].filter(el=>!el.disabled&&el.getClientRects().length);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus();}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus();}});
$('.menu-toggle').addEventListener('click',()=>{const nav=$('#main-nav');const open=!nav.classList.contains('open');nav.classList.toggle('open',open);$('.menu-toggle').setAttribute('aria-expanded',String(open));document.body.classList.toggle('no-scroll',open);});
$('#course-search').addEventListener('input',event=>{query=event.target.value.trim();renderCourses();});
$('#finish-enrollment').addEventListener('click',()=>showToast('El pago y la creación automática de tu cuenta se activan al llevar la plataforma a producción.'));
addEventListener('scroll',()=>{$('.float-stack').classList.toggle('shown',scrollY>600||cart.length>0);}, {passive:true});
addEventListener('scroll',()=>{for(const element of $$('[data-animate]:not(.in)')){const rect=element.getBoundingClientRect();if(rect.top<innerHeight*.94&&rect.bottom>0){element.classList.add('in');revealObserver?.unobserve(element);}}},{passive:true});
document.addEventListener('contextmenu',event=>event.preventDefault());
document.addEventListener('dragstart',event=>event.preventDefault());
document.addEventListener('keydown',event=>{const key=event.key.toLowerCase();if(key==='f12'||(event.ctrlKey&&event.shiftKey&&['i','j','c'].includes(key))||(event.ctrlKey&&key==='u'))event.preventDefault();});
renderCourses();updateCart();revealNew();initModelBarScroll();
