'use strict';
const WA='5491164829700',CART_KEY='babyalice_cart_v1',MAX_PUBLIC=100;
const state={products:[],cursor:null,category:'',query:'',priceMax:'',generation:0,loading:false,cart:[],cartProducts:new Map(),modalProduct:null,lastFocus:null};
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v)||0);
const image=p=>`images/${encodeURIComponent(p.imagen)}`;
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3300)}
function initModelBarScroll(){const bar=$('.gw-modelos');if(!bar)return;let timer=0,frame=0;addEventListener('scroll',()=>{if(frame)return;frame=requestAnimationFrame(()=>{frame=0;if(scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(timer);timer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)})},{passive:true})}
function initNav(){const nav=$('#mainNav'),toggle=$('#menuToggle'),close=$('#navClose'),mobile=matchMedia('(max-width: 830px)');if(!nav||!toggle)return;const sync=()=>{if(!mobile.matches){nav.inert=false;nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll')}else if(!nav.classList.contains('open'))nav.inert=true};const shut=()=>{nav.classList.remove('open');nav.inert=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll');toggle.focus()};toggle.addEventListener('click',()=>{nav.inert=false;nav.classList.add('open');toggle.setAttribute('aria-expanded','true');document.body.classList.add('no-scroll');close.focus()});close.addEventListener('click',shut);nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',shut));mobile.addEventListener('change',sync);addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open'))shut()});sync()}
function revealNew(){const nodes=$$('[data-animate]:not(.in)');if(!nodes.length)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches||!('IntersectionObserver' in window)){nodes.forEach(n=>n.classList.add('in'));return}document.documentElement.classList.add('js-motion');const io=new IntersectionObserver((entries,o)=>entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');o.unobserve(entry.target)}}),{threshold:0,rootMargin:'0px 0px 80px 0px'});nodes.forEach(n=>io.observe(n))}
async function api(params={}){const url=new URL('api/productos.php',location.href);Object.entries(params).forEach(([key,value])=>{if(value!==''&&value!=null)url.searchParams.set(key,String(value))});const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw Error('No se pudo cargar el catálogo');const data=await response.json();if(!Array.isArray(data.items)||data.items.length>100)throw Error('La respuesta superó el máximo de 100');return data}
function card(p){return `<article class="product-card" data-animate><button class="product-photo" type="button" data-detail="${esc(p.id)}" aria-label="Ver detalle de ${esc(p.nombre)}"><img src="${image(p)}" alt="${esc(p.nombre)}" loading="lazy"><span>VER DETALLE ↗</span></button><div class="product-details"><small>${esc(p.categoria)}</small><h3>${esc(p.nombre)}</h3><p class="product-price">${money(p.precio)}</p><div class="prod-actions"><div class="stepper"><button type="button" data-qty="minus" aria-label="Restar cantidad">−</button><output>1</output><button type="button" data-qty="plus" aria-label="Sumar cantidad">+</button></div><button class="prod-add" type="button" data-add="${esc(p.id)}">Agregar</button></div><p class="hint">Precio ilustrativo</p></div></article>`}
function renderCatalog(){const grid=$('#catalog-grid');grid.innerHTML=state.products.length?state.products.map(card).join(''):`<div class="empty-state"><h3>No encontramos productos</h3><p>Probá otra búsqueda o limpiá los filtros.</p><button type="button" data-clear>Ver todos los productos</button></div>`;$('#catalog-count').textContent=`${state.products.length} ${state.products.length===1?'producto':'productos'} ${state.cursor?'y más para explorar':''}`;$('#catalog-more').hidden=!state.cursor||state.loading;$('#clear-filters').hidden=!state.category&&!state.query&&!state.priceMax;revealNew()}
async function loadCatalog(reset=false){const generation=state.generation;if(reset){state.products=[];state.cursor=null;$('#catalog-grid').innerHTML='<p class="loading">Cargando productos…</p>';$('#catalog-count').textContent='Cargando productos…'}if(state.loading&&!reset)return;state.loading=true;$('#catalog-more').hidden=true;$('#catalog-error').textContent='';try{const data=await api({limit:16,scope:'catalogo',categoria:state.category,q:state.query,precio_max:state.priceMax,cursor:reset?'':state.cursor});if(generation!==state.generation)return;state.products.push(...data.items);if(state.products.length>MAX_PUBLIC)state.products.splice(0,state.products.length-MAX_PUBLIC);state.cursor=data.nextCursor;renderCatalog()}catch{if(generation===state.generation){$('#catalog-error').textContent='No pudimos cargar los productos. Intentá de nuevo.';if(!state.products.length)$('#catalog-grid').innerHTML='<div class="empty-state">El catálogo no está disponible en este momento.</div>'}}finally{if(generation===state.generation){state.loading=false;$('#catalog-more').hidden=!state.cursor}}}
function resetCatalog(){state.generation++;state.loading=false;loadCatalog(true)}
function clearFilters(){state.category='';state.query='';state.priceMax='';$('#category-select').value='';$('#price-select').value='';$('#catalog-search').value='';const hero=$('#hero-search');if(hero)hero.value='';resetCatalog()}
function selectCategory(category){state.category=category;$('#category-select').value=category;resetCatalog();$('#catalogo').scrollIntoView({behavior:'smooth'})}
function changeQuery(query){state.query=query.trim();$('#catalog-search').value=query;const hero=$('#hero-search');if(hero&&hero.value!==query)hero.value=query;resetCatalog()}
function initCatalog(){let timer=0;$('#catalog-search').addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>changeQuery(e.target.value),260)});const hero=$('#hero-search');if(hero){hero.addEventListener('input',e=>{clearTimeout(timer);timer=setTimeout(()=>changeQuery(e.target.value),260)});hero.addEventListener('keydown',e=>{if(e.key==='Enter'){e.preventDefault();changeQuery(hero.value);$('#catalogo').scrollIntoView({behavior:'smooth'})}})}$('#category-select').addEventListener('change',e=>{state.category=e.target.value;resetCatalog()});$('#price-select').addEventListener('change',e=>{state.priceMax=e.target.value;resetCatalog()});$$('[data-go-category]').forEach(b=>b.addEventListener('click',()=>selectCategory(b.dataset.goCategory)));$('#clear-filters').addEventListener('click',clearFilters);$('#catalog-more').addEventListener('click',()=>loadCatalog());$('#catalog-grid').addEventListener('click',productClick);$('#featured-rail').addEventListener('click',productClick);loadCatalog(true)}
function productClick(e){if(e.currentTarget.id==='featured-rail'&&railMoved){railMoved=false;return}const clear=e.target.closest('[data-clear]');if(clear){clearFilters();return}const detail=e.target.closest('[data-detail]');if(detail){const p=state.products.find(x=>x.id===detail.dataset.detail)||featuredProducts.find(x=>x.id===detail.dataset.detail);if(p)openModal(p);return}const step=e.target.closest('[data-qty]');if(step){const out=step.parentElement.querySelector('output');out.value=String(Math.max(1,Math.min(99,Number(out.value)+(step.dataset.qty==='plus'?1:-1))));return}const add=e.target.closest('[data-add]');if(add){const p=state.products.find(x=>x.id===add.dataset.add)||featuredProducts.find(x=>x.id===add.dataset.add);if(p)addToCart(p,Number(add.parentElement.querySelector('output').value)||1)}}
let featuredProducts=[],railMoved=false;
async function initFeatured(){const rail=$('#featured-rail');try{const data=await api({limit:8,scope:'destacados'});featuredProducts=data.items;rail.innerHTML=data.items.map(card).join('');revealNew()}catch{rail.innerHTML='<p class="loading">No pudimos mostrar la selección.</p>'}const sync=()=>{$('#rail-prev').disabled=rail.scrollLeft<=2;$('#rail-next').disabled=rail.scrollLeft+rail.clientWidth>=rail.scrollWidth-2};$('#rail-prev').addEventListener('click',()=>rail.scrollBy({left:-rail.clientWidth*.75,behavior:'smooth'}));$('#rail-next').addEventListener('click',()=>rail.scrollBy({left:rail.clientWidth*.75,behavior:'smooth'}));rail.addEventListener('scroll',sync,{passive:true});addEventListener('resize',sync);let startX=0,startScroll=0,dragging=false;rail.addEventListener('pointerdown',e=>{if(e.pointerType==='touch')return;startX=e.clientX;startScroll=rail.scrollLeft;dragging=false});rail.addEventListener('pointermove',e=>{if(e.pointerType==='touch'||!e.buttons)return;if(Math.abs(e.clientX-startX)>6){dragging=true;rail.classList.add('dragging');rail.scrollLeft=startScroll-(e.clientX-startX)}});const end=()=>{if(dragging){railMoved=true;setTimeout(()=>railMoved=false,100)}dragging=false;rail.classList.remove('dragging')};rail.addEventListener('pointerup',end);rail.addEventListener('pointercancel',end);sync()}
function readCart(){try{const raw=JSON.parse(localStorage.getItem(CART_KEY)||'[]');return Array.isArray(raw)?raw.slice(0,50).filter(x=>typeof x.id==='string'&&Number.isInteger(x.qty)&&x.qty>0&&x.qty<=99):[]}catch{return[]}}
function saveCart(){localStorage.setItem(CART_KEY,JSON.stringify(state.cart));renderCart()}
function cartMessage(){const rows=state.cart.map(x=>{const p=state.cartProducts.get(x.id);return p?`• ${p.nombre} × ${x.qty}`:''}).filter(Boolean);return `Hola Baby Alice, quisiera consultar por estos productos:\n${rows.join('\n')}\n¿Me confirman disponibilidad, precios, medios de pago y envío?`}
function renderCart(){const count=state.cart.reduce((n,x)=>n+x.qty,0);$$('[data-cart-count]').forEach(el=>el.textContent=count);$('#floating-actions').classList.toggle('visible',scrollY>600||count>0);const rows=state.cart.map(x=>{const p=state.cartProducts.get(x.id);return p?`<div class="cart-row"><img src="${image(p)}" alt=""><div><h3>${esc(p.nombre)}</h3><small>${x.qty} × ${money(p.precio)}</small></div><button type="button" data-remove="${esc(x.id)}">Quitar</button></div>`:''}).join('');$('#cart-items').innerHTML=rows||'<div class="empty-state"><h3>Tu carrito está vacío</h3><p>Explorá el catálogo y sumá lo que te interese.</p><button type="button" data-cart-close>Volver a productos</button></div>';const total=state.cart.reduce((n,x)=>n+(state.cartProducts.get(x.id)?.precio||0)*x.qty,0);$('#cart-total').textContent=money(total);$('#checkout-button').disabled=!rows;$('#cart-whatsapp').href=`https://wa.me/${WA}?text=${encodeURIComponent(cartMessage())}`}
async function hydrateCart(){state.cart=readCart();if(state.cart.length){try{const data=await api({limit:50,ids:state.cart.map(x=>x.id).join(',')});data.items.forEach(p=>state.cartProducts.set(p.id,p));state.cart=state.cart.filter(x=>state.cartProducts.has(x.id))}catch{state.cart=[]}}renderCart()}
function addToCart(p,qty=1){state.cartProducts.set(p.id,p);const found=state.cart.find(x=>x.id===p.id);if(found)found.qty=Math.min(99,found.qty+qty);else state.cart.push({id:p.id,qty:Math.min(99,qty)});saveCart();toast(`${p.nombre} se agregó al carrito`)}
function openLayer(el){state.lastFocus=document.activeElement;$('#overlay').hidden=false;el.hidden=false;document.body.classList.add('no-scroll');$('#floating-actions').style.visibility='hidden';el.querySelector('button,a')?.focus()}
function closeLayers(){const modalOpen=!$('#product-modal').hidden;$('#overlay').hidden=true;$('#cart-drawer').hidden=true;$('#product-modal').hidden=true;document.body.classList.remove('no-scroll');$('#floating-actions').style.visibility='';if(modalOpen){const url=new URL(location.href);url.searchParams.delete('producto');history.replaceState(null,'',url)}state.lastFocus?.focus()}
function openModal(p){state.modalProduct=p;const related=[...state.products,...featuredProducts].filter((x,i,a)=>x.id!==p.id&&x.categoria===p.categoria&&a.findIndex(y=>y.id===x.id)===i).slice(0,3);$('#modal-body').innerHTML=`<div class="modal-layout"><img src="${image(p)}" alt="${esc(p.nombre)}"><div class="modal-info"><span class="eyebrow">${esc(p.categoria)}</span><h2 id="modal-title">${esc(p.nombre)}</h2><p>${esc(p.detalle)}</p><div class="modal-price">${money(p.precio)}</div><p>Precio ilustrativo de esta demo. Consultá disponibilidad y detalles reales.</p><div class="prod-actions"><div class="stepper"><button type="button" data-modal-qty="minus" aria-label="Restar cantidad">−</button><output id="modal-qty">1</output><button type="button" data-modal-qty="plus" aria-label="Sumar cantidad">+</button></div><button class="prod-add" id="modal-add" type="button">Agregar al carrito</button></div><button class="btn btn-outline" id="modal-buy" type="button">Comprar ahora</button>${related.length?`<div class="related">También te puede interesar${related.map(x=>`<button type="button" data-related="${esc(x.id)}">${esc(x.nombre)} ↗</button>`).join('')}</div>`:''}</div></div>`;openLayer($('#product-modal'));const url=new URL(location.href);url.searchParams.set('producto',p.id);history.replaceState(null,'',url)}
function initDrawers(){hydrateCart();addEventListener('scroll',()=>$('#floating-actions').classList.toggle('visible',scrollY>600||state.cart.length>0),{passive:true});$$('[data-open-cart]').forEach(b=>b.addEventListener('click',()=>openLayer($('#cart-drawer'))));$$('[data-close]').forEach(b=>b.addEventListener('click',closeLayers));$('#overlay').addEventListener('click',closeLayers);$('#cart-items').addEventListener('click',e=>{const remove=e.target.closest('[data-remove]');if(remove){state.cart=state.cart.filter(x=>x.id!==remove.dataset.remove);saveCart()}if(e.target.closest('[data-cart-close]')){closeLayers();$('#catalogo').scrollIntoView({behavior:'smooth'})}});$('#modal-body').addEventListener('click',e=>{const q=e.target.closest('[data-modal-qty]');if(q){const out=$('#modal-qty');out.value=String(Math.max(1,Math.min(99,Number(out.value)+(q.dataset.modalQty==='plus'?1:-1))))}const rel=e.target.closest('[data-related]');if(rel){const p=[...state.products,...featuredProducts].find(x=>x.id===rel.dataset.related);if(p)openModal(p)}if(e.target.closest('#modal-add')&&state.modalProduct){addToCart(state.modalProduct,Number($('#modal-qty').value)||1);closeLayers()}if(e.target.closest('#modal-buy')&&state.modalProduct){addToCart(state.modalProduct,Number($('#modal-qty').value)||1);closeLayers();openLayer($('#cart-drawer'))}});$('#checkout-button').addEventListener('click',()=>toast('El pago online se activa al pasar la tienda a producción. Consultá tu selección por WhatsApp.'));addEventListener('keydown',e=>{const open=!$('#cart-drawer').hidden?$('#cart-drawer'):!$('#product-modal').hidden?$('#product-modal'):null;if(!open)return;if(e.key==='Escape'){closeLayers();return}if(e.key==='Tab'){const focusable=[...open.querySelectorAll('button:not([disabled]),a[href],input,select')];const first=focusable[0],last=focusable.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}})}
async function initProductLink(){const id=new URL(location.href).searchParams.get('producto');if(!id)return;try{const data=await api({limit:1,id});if(data.items[0])openModal(data.items[0])}catch{}}
document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='f12'||(e.ctrlKey&&e.shiftKey&&['i','j','c'].includes(k))||(e.ctrlKey&&k==='u'))e.preventDefault()});
initModelBarScroll();initNav();initDrawers();initCatalog();initFeatured();initProductLink();revealNew();
