'use strict';
const MAX_PAGE=100;
const MAX_BUFFER=300;
const SEARCH_TARGET=20;
const state={items:[],cursor:null,loading:false,dropped:false,searching:false,generation:0};
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const norm=s=>String(s??'').toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const matches=(p,q)=>norm([p.nombre,p.categoria,p.equipo,p.detalle].join(' ')).includes(norm(q));
async function page(cursor){const url=new URL('api/productos.php',location.href);url.searchParams.set('limit',String(MAX_PAGE));url.searchParams.set('scope','admin');if(cursor)url.searchParams.set('cursor',cursor);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error('No se pudo cargar la página');const data=await response.json();if(!Array.isArray(data.items)||data.items.length>MAX_PAGE)throw new Error('El servidor superó el límite de 100');return data}
function render(){const query=document.getElementById('admin-search').value.trim();const filtered=query?state.items.filter(p=>matches(p,query)):state.items;const rows=document.getElementById('admin-rows');rows.innerHTML=filtered.length?filtered.map(p=>`<tr><td><div class="prod-cell"><img src="images/${encodeURIComponent(p.imagen)}" alt="" width="54" height="54"><div>${esc(p.nombre)}<small>${esc(p.id)}</small></div></div></td><td>${esc(p.categoria)}</td><td>${esc(p.equipo)}</td><td><span class="pill">Publicado</span></td></tr>`).join(''):`<tr><td colspan="4">${query?'No encontramos coincidencias en las páginas consultadas.':'Todavía no hay productos.'}</td></tr>`;document.getElementById('admin-count').textContent=`${filtered.length} ${filtered.length===1?'resultado':'resultados'} en ${state.items.length} cargados`;const more=document.getElementById('admin-more');more.hidden=!state.cursor;more.disabled=state.loading;document.getElementById('admin-note').textContent=state.dropped?'Se muestran hasta 300 productos recientes para no guardar la colección completa en el navegador.':state.searching?'Buscando en páginas adicionales solo si hacen falta coincidencias.':'Cada consulta al servidor trae hasta 100 productos.'}
async function loadMore(){if(state.loading||!state.cursor)return;state.loading=true;render();try{const data=await page(state.cursor);state.items.push(...data.items);state.cursor=data.nextCursor;if(state.items.length>MAX_BUFFER){state.items.splice(0,state.items.length-MAX_BUFFER);state.dropped=true}render()}catch{document.getElementById('admin-note').textContent='No pudimos cargar más productos. Volvé a intentar.'}finally{state.loading=false;render()}}
async function searchMore(){const generation=++state.generation;const input=document.getElementById('admin-search');const query=input.value.trim();if(!query){state.searching=false;render();return}if(state.dropped){state.items=[];state.cursor=null;state.dropped=false;try{const data=await page(null);if(generation!==state.generation)return;state.items=data.items;state.cursor=data.nextCursor}catch{render();return}}state.searching=true;render();while(generation===state.generation&&state.cursor&&state.items.filter(p=>matches(p,query)).length<SEARCH_TARGET){if(state.loading){await new Promise(resolve=>setTimeout(resolve,30));continue}await loadMore()}if(generation===state.generation){state.searching=false;render()}}
async function init(){try{const first=await page(null);state.items=first.items;state.cursor=first.nextCursor;render()}catch{document.getElementById('admin-rows').innerHTML='<tr><td colspan="4">No pudimos cargar el catálogo. Revisá la conexión.</td></tr>';document.getElementById('admin-count').textContent='Error de carga'}let timer=0;document.getElementById('admin-search').addEventListener('input',()=>{state.generation++;clearTimeout(timer);timer=setTimeout(searchMore,220)});document.getElementById('admin-more').addEventListener('click',loadMore)}
init();
