'use strict';
const API = 'api/productos.php';
const WHATSAPP = 'https://wa.me/5492804998845';
const esc = s => String(s ?? '').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
const productMap = new Map();
const remember = items => items.forEach(p => productMap.set(p.id,p));
const getProducto = id => productMap.get(id);
const Cart = {
  KEY:'nickyritmosargentina_cart',
  get(){try{const raw=JSON.parse(localStorage.getItem(this.KEY));return Array.isArray(raw)?raw.filter(x=>typeof x.id==='string'&&Number.isInteger(x.qty)&&x.qty>0).slice(0,100):[]}catch{return[]}},
  save(items){localStorage.setItem(this.KEY,JSON.stringify(items));document.dispatchEvent(new CustomEvent('cart:updated'))},
  add(producto,qty=1){const items=this.get();const existing=items.find(i=>i.id===producto.id);if(existing)existing.qty=Math.min(existing.qty+qty,99);else items.push({id:producto.id,qty:Math.min(qty,99)});this.save(items)},
  remove(id){this.save(this.get().filter(i=>i.id!==id))},
  count(){return this.get().reduce((n,i)=>n+i.qty,0)}
};
const reduceMotion=matchMedia('(prefers-reduced-motion: reduce)').matches;
let revealsListos=false;
let toastTimer=0;
function toast(message){const el=document.getElementById('toast');if(!el)return;el.textContent=message;el.hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>el.hidden=true,3300)}
function initModelBarScroll(){const bar=document.querySelector('.gw-modelos');if(!bar)return;let showTimer=0,frame=0;const update=()=>{frame=0;if(scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(showTimer);showTimer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)};addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(update)},{passive:true})}
function revelarNuevos(cont){if(!revealsListos||!cont)return;const nuevos=[...cont.querySelectorAll('[data-animate]:not(.in)')];if(!nuevos.length)return;if(reduceMotion){nuevos.forEach(el=>el.classList.add('in'));return}requestAnimationFrame(()=>requestAnimationFrame(()=>nuevos.forEach((el,i)=>{const d=Math.min(i*.06,.6);el.style.transitionDelay=`${d}s`;el.classList.add('in');setTimeout(()=>el.style.transitionDelay='',(d+1.2)*1000)})))}
function initReveals(){revealsListos=true;const items=document.querySelectorAll('[data-animate]');if(!items.length)return;if(!('IntersectionObserver'in window)||reduceMotion){items.forEach(el=>el.classList.add('in'));return}const entrar=(el,n)=>{const d=Math.min(n*.1,.6);el.style.transitionDelay=`${d}s`;el.classList.add('in');setTimeout(()=>el.style.transitionDelay='',(d+1.2)*1000)};const io=new IntersectionObserver(entries=>{let n=0;entries.forEach(entry=>{if(entry.isIntersecting){entrar(entry.target,n++);io.unobserve(entry.target)}})},{threshold:0,rootMargin:'0px 0px -7% 0px'});items.forEach(el=>io.observe(el));let queued=false;const sweep=()=>{queued=false;let pending=0,n=0;items.forEach(el=>{if(el.classList.contains('in'))return;const r=el.getBoundingClientRect();if(r.bottom>0&&r.top<innerHeight){entrar(el,n++);io.unobserve(el)}else pending++});if(!pending){removeEventListener('scroll',queueSweep);removeEventListener('resize',queueSweep)}};const queueSweep=()=>{if(!queued){queued=true;requestAnimationFrame(sweep)}};requestAnimationFrame(()=>requestAnimationFrame(queueSweep));addEventListener('load',queueSweep);addEventListener('scroll',queueSweep,{passive:true});addEventListener('resize',queueSweep,{passive:true})}
async function fetchPage(params={}){const url=new URL(API,location.href);Object.entries(params).forEach(([key,value])=>{if(value!==undefined&&value!==null&&value!=='')url.searchParams.set(key,String(value))});const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw new Error(`Catálogo: ${response.status}`);const data=await response.json();if(!Array.isArray(data.items)||data.items.length>100)throw new Error('Respuesta de catálogo inválida');remember(data.items);return data}
function cardHTML(p,featured=false){const img=`images/${encodeURIComponent(p.imagen)}`;return `<article class="product-card" data-animate="subir" style="opacity:0;transform:translateY(48px)"><button class="product-image" type="button" data-detail="${esc(p.id)}" aria-label="Ver ${esc(p.nombre)}"><img src="${img}" alt="Portada de ${esc(p.nombre)}" width="800" height="800" loading="lazy"></button><div class="product-content"><span class="product-kicker">${esc(p.categoria)}</span><h3 class="product-title">${esc(p.nombre)}</h3><p class="product-equipment">${esc(p.equipo)}</p><div class="product-bottom"><span class="product-price">Precio a consultar</span><div class="prod-actions"><button class="prod-info" type="button" data-detail="${esc(p.id)}" aria-label="Ver detalles de ${esc(p.nombre)}">↗</button><button class="prod-add" type="button" data-add="${esc(p.id)}">Agregar</button></div></div></div></article>`}
const catalog={cursor:null,category:'',query:'',loading:false,serial:0,shown:0};
async function loadCatalog(reset=false){if(catalog.loading&&!reset)return;const serial=++catalog.serial;if(reset){catalog.cursor=null;catalog.shown=0;document.getElementById('product-grid').innerHTML='<p class="loading">Buscando sonidos...</p>'}catalog.loading=true;const more=document.getElementById('catalog-more');more.hidden=true;try{const data=await fetchPage({scope:'catalogo',limit:16,cursor:catalog.cursor,categoria:catalog.category,q:catalog.query});if(serial!==catalog.serial)return;const grid=document.getElementById('product-grid');if(reset)grid.innerHTML='';grid.insertAdjacentHTML('beforeend',data.items.map(p=>cardHTML(p)).join(''));revelarNuevos(grid);catalog.shown+=data.items.length;catalog.cursor=data.nextCursor;more.hidden=!data.nextCursor;document.getElementById('catalog-empty').hidden=catalog.shown>0;document.getElementById('results-count').textContent=`${catalog.shown} ${catalog.shown===1?'producto':'productos'}`;if(window.ScrollTrigger)ScrollTrigger.refresh()}catch(error){if(serial===catalog.serial){document.getElementById('product-grid').innerHTML='<p class="loading">No pudimos cargar el catálogo. Probá de nuevo.</p>';toast('No pudimos cargar el catálogo')}}finally{if(serial===catalog.serial)catalog.loading=false}}
async function loadFeatured(){const grid=document.getElementById('featured-grid');try{const data=await fetchPage({scope:'destacados',limit:6});grid.innerHTML=data.items.map(p=>cardHTML(p,true)).join('');revelarNuevos(grid)}catch{grid.innerHTML='<p class="loading">No pudimos cargar los destacados.</p>'}}
function setCategory(category){catalog.category=category;document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===category));loadCatalog(true);document.getElementById('tienda')?.scrollIntoView({behavior:reduceMotion?'instant':'smooth',block:'start'})}
function initCatalog(){document.querySelectorAll('[data-filter]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.filter)));document.querySelectorAll('[data-cat]').forEach(b=>b.addEventListener('click',()=>setCategory(b.dataset.cat)));document.getElementById('clear-filters')?.addEventListener('click',resetCatalog);document.getElementById('empty-reset')?.addEventListener('click',resetCatalog);document.getElementById('catalog-more')?.addEventListener('click',()=>loadCatalog(false));const search=document.getElementById('catalog-search');let timer=0;search?.addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(()=>{catalog.query=search.value.trim();loadCatalog(true)},280)});document.getElementById('search-form')?.addEventListener('submit',event=>{event.preventDefault();clearTimeout(timer);catalog.query=search.value.trim();loadCatalog(true)});document.querySelectorAll('[data-go-search]').forEach(b=>b.addEventListener('click',()=>{document.getElementById('tienda')?.scrollIntoView({behavior:'smooth'});setTimeout(()=>search?.focus(),350)}));loadCatalog(true);loadFeatured()}
function resetCatalog(){catalog.category='';catalog.query='';document.getElementById('catalog-search').value='';document.querySelectorAll('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===''));loadCatalog(true)}
let returnFocus=null;
function lock(){document.body.classList.add('no-scroll');document.getElementById('floats')?.setAttribute('hidden','')}
function unlock(){document.body.classList.remove('no-scroll');document.getElementById('floats')?.removeAttribute('hidden')}
async function ensureCartProducts(){const missing=Cart.get().map(i=>i.id).filter(id=>!productMap.has(id));if(!missing.length)return;try{await fetchPage({ids:missing.join(','),limit:Math.min(100,missing.length)})}catch{}}
async function renderCart(){await ensureCartProducts();const lines=document.getElementById('cart-lines');const items=Cart.get();if(!items.length){lines.innerHTML='<div class="cart-empty"><h3>Tu carrito espera el primer sonido</h3><p>Explorá los packs y guardá los que te interesen.</p><a class="text-link" href="#tienda" data-close-cart>Ver el catálogo ↗</a></div>'}else{lines.innerHTML=items.map(i=>{const p=getProducto(i.id);return p?`<div class="cart-line"><img src="images/${encodeURIComponent(p.imagen)}" alt="" width="65" height="65"><div><strong>${esc(p.nombre)}</strong><small>${i.qty} ${i.qty===1?'pack':'packs'}</small></div><button type="button" data-remove="${esc(i.id)}" aria-label="Quitar ${esc(p.nombre)}">×</button></div>`:''}).join('')}const message=items.length?`Hola Nicky, quiero consultar por estos productos: ${items.map(i=>`${getProducto(i.id)?.nombre||i.id} x${i.qty}`).join(', ')}. ¿Me pasás precios y detalles de entrega?`:'Hola Nicky, quiero consultar por tus productos digitales.';document.getElementById('cart-consult').href=`${WHATSAPP}?text=${encodeURIComponent(message)}`}
async function openCart(){returnFocus=document.activeElement;await renderCart();document.getElementById('cart-overlay').hidden=false;document.getElementById('cart-drawer').hidden=false;lock();document.querySelector('#cart-drawer .close-btn')?.focus()}
function closeCart(){document.getElementById('cart-overlay').hidden=true;document.getElementById('cart-drawer').hidden=true;unlock();returnFocus?.focus()}
function openModal(id){const p=getProducto(id);if(!p)return;returnFocus=document.activeElement;const box=document.getElementById('modal-content');box.innerHTML=`<div class="modal-content"><img src="images/${encodeURIComponent(p.imagen)}" alt="Portada de ${esc(p.nombre)}" width="900" height="900"><div class="modal-copy"><span class="product-kicker">${esc(p.categoria)}</span><h2>${esc(p.nombre)}</h2><p>${esc(p.detalle)}</p><p class="modal-equipment"><strong>Compatible con</strong><br>${esc(p.equipo)}</p><div class="modal-actions"><button class="btn btn-primary" type="button" data-add="${esc(p.id)}">Agregar al carrito</button><a class="btn btn-outline" href="${WHATSAPP}?text=${encodeURIComponent(`Hola Nicky, quiero consultar por ${p.nombre}. Mi equipo es: `)}" target="_blank" rel="noopener">Consultar ↗</a></div></div></div>`;document.getElementById('product-modal').hidden=false;lock();document.querySelector('.modal-close')?.focus();history.replaceState(null,'',`?producto=${encodeURIComponent(p.id)}${location.hash}`)}
function closeModal(){document.getElementById('product-modal').hidden=true;unlock();returnFocus?.focus();if(new URL(location.href).searchParams.has('producto'))history.replaceState(null,'',location.pathname+location.hash)}
function syncCart(){const n=Cart.count();document.querySelectorAll('[data-cart-count]').forEach(el=>{el.textContent=n;el.hidden=n===0});document.getElementById('cart-float')?.classList.toggle('visible',n>0||scrollY>600);if(!document.getElementById('cart-drawer').hidden)renderCart()}
function initInteractions(){document.addEventListener('click',event=>{const add=event.target.closest('[data-add]');if(add){const p=getProducto(add.dataset.add);if(p){Cart.add(p);toast(`${p.nombre} agregado al carrito`)}return}const detail=event.target.closest('[data-detail]');if(detail){openModal(detail.dataset.detail);return}const remove=event.target.closest('[data-remove]');if(remove){Cart.remove(remove.dataset.remove);return}if(event.target.closest('[data-open-cart]')){openCart();return}if(event.target.closest('[data-close-cart]')){closeCart();return}if(event.target.closest('[data-close-modal]')){closeModal();return}});document.getElementById('cart-overlay')?.addEventListener('click',closeCart);document.addEventListener('keydown',event=>{if(event.key==='Escape'){if(!document.getElementById('product-modal').hidden)closeModal();else if(!document.getElementById('cart-drawer').hidden)closeCart();else closeNav()}if(event.key==='Tab'){const open=!document.getElementById('product-modal').hidden?document.querySelector('.product-modal'):!document.getElementById('cart-drawer').hidden?document.getElementById('cart-drawer'):null;if(!open)return;const focusable=[...open.querySelectorAll('a,button,input')].filter(x=>!x.disabled);if(!focusable.length)return;const first=focusable[0],last=focusable.at(-1);if(event.shiftKey&&document.activeElement===first){event.preventDefault();last.focus()}else if(!event.shiftKey&&document.activeElement===last){event.preventDefault();first.focus()}}});document.addEventListener('cart:updated',syncCart);const floatUpdate=()=>{const visible=scrollY>600||Cart.count()>0;document.getElementById('cart-float')?.classList.toggle('visible',visible);document.getElementById('wsp-float')?.classList.toggle('visible',visible)};addEventListener('scroll',floatUpdate,{passive:true});floatUpdate();syncCart();const productId=new URL(location.href).searchParams.get('producto');if(productId){let attempts=0;const tryOpen=()=>{const product=getProducto(productId);if(product){openModal(productId);return}if(++attempts<20)setTimeout(tryOpen,200)};setTimeout(tryOpen,400)}}
function closeNav(){const nav=document.getElementById('mobile-nav');nav.hidden=true;document.querySelector('.menu-toggle')?.setAttribute('aria-expanded','false');unlock()}
function initNav(){const toggle=document.querySelector('.menu-toggle'),nav=document.getElementById('mobile-nav');toggle?.addEventListener('click',()=>{const open=nav.hidden;nav.hidden=!open;toggle.setAttribute('aria-expanded',String(open));if(open){lock();nav.querySelector('.nav-close')?.focus()}else unlock()});nav?.querySelector('.nav-close')?.addEventListener('click',closeNav);nav?.querySelectorAll('a').forEach(a=>a.addEventListener('click',closeNav))}
initModelBarScroll();initNav();initInteractions();initCatalog();initReveals();
