'use strict';
const esc=s=>String(s??'').replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;').replace(/'/g,'&#39;');
function showToast(msg){let wrap=document.querySelector('.toast-wrap');if(!wrap){wrap=document.createElement('div');wrap.className='toast-wrap';wrap.setAttribute('aria-live','polite');document.body.appendChild(wrap)}const toast=document.createElement('div');toast.className='toast';toast.setAttribute('role','status');toast.innerHTML=`<svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2.5"><path d="M20 6L9 17l-5-5"/></svg><span>${esc(msg)}</span>`;wrap.appendChild(toast);setTimeout(()=>{toast.classList.add('hiding');setTimeout(()=>toast.remove(),220)},3200)}
function initModelBarScroll(){const bar=document.querySelector('.gw-modelos');if(!bar)return;let showTimer=0,frame=0;const update=()=>{frame=0;if(window.scrollY<=8){bar.classList.remove('gw-modelos--scrolling');return}bar.classList.add('gw-modelos--scrolling');clearTimeout(showTimer);showTimer=setTimeout(()=>bar.classList.remove('gw-modelos--scrolling'),120)};addEventListener('scroll',()=>{if(!frame)frame=requestAnimationFrame(update)},{passive:true})}
function initWspFloat(){const btn=document.getElementById('wsp-float');if(!btn)return;let shown=false;window.addEventListener('scroll',()=>{if(window.scrollY>600&&!shown){shown=true;btn.classList.add('visible')}},{passive:true})}
function initNav(){const nav=document.getElementById('mainNav'),toggle=document.getElementById('menuToggle'),close=document.getElementById('navClose');if(!nav||!toggle)return;const mobile=matchMedia('(max-width: 830px)');const sync=()=>{if(!mobile.matches){nav.inert=false;nav.classList.remove('open');toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll')}else if(!nav.classList.contains('open'))nav.inert=true};const shut=()=>{nav.classList.remove('open');nav.inert=true;toggle.setAttribute('aria-expanded','false');document.body.classList.remove('no-scroll');toggle.focus()};toggle.addEventListener('click',()=>{nav.inert=false;nav.classList.add('open');toggle.setAttribute('aria-expanded','true');document.body.classList.add('no-scroll');close.focus()});close.addEventListener('click',shut);nav.querySelectorAll('a').forEach(a=>a.addEventListener('click',shut));mobile.addEventListener('change',sync);sync();document.addEventListener('keydown',e=>{if(e.key==='Escape'&&nav.classList.contains('open'))shut()})}
function initReveals(){const els=[...document.querySelectorAll('[data-animate]')];if(!els.length)return;if(matchMedia('(prefers-reduced-motion: reduce)').matches){els.forEach(el=>el.classList.add('in'));return}document.documentElement.classList.add('js-motion');if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>{entries.forEach(entry=>{if(entry.isIntersecting){entry.target.classList.add('in');io.unobserve(entry.target)}})},{threshold:.08,rootMargin:'0px 0px -20px 0px'});els.forEach(el=>io.observe(el))}else els.forEach(el=>el.classList.add('in'))}
function initContact(){const form=document.getElementById('contactForm');if(!form)return;const error=document.getElementById('formError');const fail=(msg,el)=>{error.textContent=msg;error.hidden=false;el?.focus();showToast(msg)};form.addEventListener('submit',event=>{event.preventDefault();error.hidden=true;const name=form.elements.nombre.value.trim(),therapy=form.elements.terapia.value,notes=form.elements.mensaje.value.trim();if(!name)return fail('Escribí tu nombre.',form.elements.nombre);if(!therapy)return fail('Elegí la terapia que querés consultar.',form.elements.terapia);const message=`Hola, soy ${name}. Quiero consultar por ${therapy}.${notes?` Mi consulta: ${notes}`:''} ¿Podrían contarme la disponibilidad y la ubicación?`;const link=document.createElement('a');link.href=`https://wa.me/5492634565360?text=${encodeURIComponent(message)}`;link.target='_blank';link.rel='noopener';document.body.appendChild(link);link.click();link.remove();showToast('La consulta se abrió en WhatsApp')})}
function initFaq(){document.querySelectorAll('.faq details').forEach(el=>el.addEventListener('toggle',()=>{if(typeof ScrollTrigger!=='undefined')ScrollTrigger.refresh()}))}
document.addEventListener('contextmenu',e=>e.preventDefault());document.addEventListener('dragstart',e=>e.preventDefault());document.addEventListener('keydown',e=>{const k=e.key.toLowerCase();if(k==='f12'||(e.ctrlKey&&e.shiftKey&&['i','j','c'].includes(k))||(e.ctrlKey&&k==='u'))e.preventDefault()});
if(typeof gsap!=='undefined'&&typeof ScrollTrigger!=='undefined')gsap.registerPlugin(ScrollTrigger);if(typeof gsap==='undefined')document.querySelectorAll('[data-animate]').forEach(el=>el.classList.add('in'));if(typeof ScrollTrigger!=='undefined')window.addEventListener('load',()=>ScrollTrigger.refresh());
initModelBarScroll();initWspFloat();initNav();initReveals();initContact();initFaq();
