'use strict';
const API='api/productos.php',PAGE_SIZE=16,CAP=100,CART_KEY='regalaplantas_cart_v1';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const money=n=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(n)||0);
const state={category:'',query:'',price:'',cursor:null,count:0,generation:0,loading:false,products:new Map(),cart:{},active:null,previousFocus:null};
try{const raw=JSON.parse(localStorage.getItem(CART_KEY)||'{}');if(raw&&typeof raw==='object'&&!Array.isArray(raw))for(const [id,q] of Object.entries(raw))if(/^planta-\d+$/.test(id)&&Number.isInteger(q)&&q>0&&q<=99)state.cart[id]=q}catch{}
function toast(message){const el=$('#toast');el.textContent=message;el.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>el.classList.remove('show'),3200)}
function saveCart(){try{localStorage.setItem(CART_KEY,JSON.stringify(state.cart))}catch{}updateCart()}
function cartCount(){return Object.values(state.cart).reduce((a,b)=>a+b,0)}
function updateCart(){$$('[data-cart-count]').forEach(el=>el.textContent=cartCount());$('.float-actions').classList.toggle('shown',scrollY>600||cartCount()>0);renderCart()}
async function fetchPage(params={}){const u=new URL(API,location.href);for(const [k,v] of Object.entries(params))if(v!==''&&v!=null)u.searchParams.set(k,v);const r=await fetch(u,{headers:{Accept:'application/json'}});if(!r.ok)throw Error('No se pudo cargar el catálogo');const d=await r.json();if(!Array.isArray(d.items)||d.items.length>100)throw Error('Respuesta fuera de límite');d.items.forEach(p=>{state.products.delete(p.id);state.products.set(p.id,p)});while(state.products.size>200){const oldest=state.products.keys().next().value;if(state.cart[oldest])break;state.products.delete(oldest)}return d}
const img=p=>`images/${encodeURIComponent(p.imagen)}`;
function productCard(p,featured=false){return `<article class="product-card" data-id="${esc(p.id)}"><img class="product-image" src="${img(p)}" alt="Imagen ilustrativa de ${esc(p.categoria.toLowerCase())}" loading="lazy" data-detail="${esc(p.id)}"><div class="product-info"><span class="product-category">${esc(p.categoria)}</span><button class="product-title" type="button" data-detail="${esc(p.id)}">${esc(p.nombre)}</button><span class="product-price">${money(p.precio)}</span><div class="prod-actions"><div class="stepper"><button type="button" data-step="-1" aria-label="Quitar una unidad">−</button><output>1</output><button type="button" data-step="1" aria-label="Sumar una unidad">+</button></div><button class="prod-add" type="button" data-add="${esc(p.id)}">Agregar</button></div><button class="prod-buy" type="button" data-buy="${esc(p.id)}">Comprar ahora ↗</button></div></article>`}
function renderProducts(items,append=false){const grid=$('#catalog-grid');if(!append)grid.innerHTML='';grid.insertAdjacentHTML('beforeend',items.map(p=>productCard(p)).join(''));if(!grid.children.length)grid.innerHTML='<p class="loading">No encontramos productos con esos filtros. Probá con otra búsqueda.</p>';$('#result-count').textContent=`${state.count} ${state.count===1?'producto':'productos'} mostrados`;$('#load-more').hidden=!state.cursor||state.count>=CAP}
function getFilters(){return{limit:String(Math.min(PAGE_SIZE,CAP-state.count)),categoria:state.category,q:state.query,precio_max:state.price,cursor:state.cursor}}
async function loadCatalog(reset=false){if(reset){state.generation++;state.count=0;state.cursor=null;$('#catalog-grid').innerHTML='<p class="loading">Buscando plantas…</p>'}else if(state.loading)return;const generation=state.generation;state.loading=true;$('#load-more').disabled=true;$('#catalog-error').textContent='';try{const d=await fetchPage(getFilters());if(generation!==state.generation)return;const items=d.items.slice(0,CAP-state.count);state.count+=items.length;state.cursor=state.count>=CAP?null:d.nextCursor;renderProducts(items,!reset)}catch{if(generation===state.generation){$('#catalog-error').textContent='No pudimos cargar esta página. Intentá nuevamente.';if(reset)$('#catalog-grid').innerHTML=''}}finally{if(generation===state.generation){state.loading=false;$('#load-more').disabled=false}}}
async function featured(){try{const d=await fetchPage({scope:'destacados',limit:'8'});$('#featured-grid').innerHTML=d.items.map(p=>productCard(p,true)).join('')}catch{$('#featured-grid').innerHTML='<p>No pudimos cargar los destacados.</p>'}}
function qty(card){return Math.max(1,Math.min(99,Number(card.querySelector('output').textContent)||1))}
function add(id,amount=1,open=false){if(!state.products.has(id))return;state.cart[id]=Math.min(99,(state.cart[id]||0)+amount);saveCart();if(open)openCart();else toast('Agregado al carrito')}
function renderCart(){const box=$('#cart-items');if(!box)return;const entries=Object.entries(state.cart).filter(([id])=>state.products.has(id));box.innerHTML=entries.length?entries.map(([id,q])=>{const p=state.products.get(id);return `<div class="cart-line"><img src="${img(p)}" alt=""><div><strong>${esc(p.nombre)}</strong><small>${q} × ${money(p.precio)}</small><br><button type="button" data-remove="${esc(id)}">Quitar</button></div><b>${money(p.precio*q)}</b></div>`}).join(''):'<p>Tu carrito todavía está vacío. Elegí una planta para empezar.</p>';$('#cart-total').textContent=money(entries.reduce((a,[id,q])=>a+state.products.get(id).precio*q,0))}
function openLayer(el){state.previousFocus=document.activeElement;$('#overlay').hidden=false;el.hidden=false;document.body.classList.add('lock');$('.model-switch').classList.add('is-hidden');$('.float-actions').style.display='none';el.querySelector('button')?.focus()}
function closeLayers(){const had=!$('#overlay').hidden;$('#cart-drawer').hidden=true;$('#product-modal').hidden=true;$('#overlay').hidden=true;document.body.classList.remove('lock');$('.float-actions').style.display='';if(had)state.previousFocus?.focus()}
function openCart(){closeLayers();renderCart();openLayer($('#cart-drawer'))}
function showProduct(id){const p=state.products.get(id);if(!p)return;$('#modal-content').innerHTML=`<div class="modal-grid"><img src="${img(p)}" alt="Imagen ilustrativa de ${esc(p.categoria.toLowerCase())}"><div class="modal-copy"><p class="eyebrow">${esc(p.categoria)}</p><h2>${esc(p.nombre)}</h2><p>${esc(p.detalle)}</p><p>Imagen, precio y disponibilidad ilustrativos de esta demo. Consultá las opciones reales por WhatsApp.</p><strong>${money(p.precio)}</strong><button class="button primary" type="button" data-modal-add="${esc(p.id)}">Agregar al carrito ↗</button></div></div>`;openLayer($('#product-modal'))}
async function hydrateCart(){const ids=Object.keys(state.cart).slice(0,50);if(!ids.length)return;try{await fetchPage({ids:ids.join(','),limit:'50'});renderCart()}catch{}}
document.addEventListener('click',e=>{const step=e.target.closest('[data-step]');if(step){const out=step.parentElement.querySelector('output');out.textContent=Math.max(1,Math.min(99,(Number(out.textContent)||1)+Number(step.dataset.step)));return}const category=e.target.closest('[data-category]');if(category){state.category=category.dataset.category;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b.dataset.filter===state.category));loadCatalog(true);$('#tienda').scrollIntoView({behavior:'smooth'});return}const filter=e.target.closest('[data-filter]');if(filter){state.category=filter.dataset.filter;$$('[data-filter]').forEach(b=>b.classList.toggle('active',b===filter));loadCatalog(true);return}const addButton=e.target.closest('[data-add],[data-buy]');if(addButton){const card=addButton.closest('.product-card');add(addButton.dataset.add||addButton.dataset.buy,qty(card),Boolean(addButton.dataset.buy));return}const detail=e.target.closest('[data-detail]');if(detail){showProduct(detail.dataset.detail);return}const remove=e.target.closest('[data-remove]');if(remove){delete state.cart[remove.dataset.remove];saveCart();return}const modalAdd=e.target.closest('[data-modal-add]');if(modalAdd){add(modalAdd.dataset.modalAdd);closeLayers();return}if(e.target.closest('[data-open-cart]'))openCart();if(e.target.closest('[data-close]')||e.target.id==='overlay')closeLayers()});
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeLayers();if(e.key==='Tab'){const layer=!$('#product-modal').hidden?$('#product-modal'):!$('#cart-drawer').hidden?$('#cart-drawer'):null;if(!layer)return;const focus=[...layer.querySelectorAll('button,a,input')].filter(n=>!n.disabled&&n.offsetParent);if(!focus.length)return;const first=focus[0],last=focus.at(-1);if(e.shiftKey&&document.activeElement===first){e.preventDefault();last.focus()}else if(!e.shiftKey&&document.activeElement===last){e.preventDefault();first.focus()}}});
let searchTimer;$('#catalog-search').addEventListener('input',e=>{clearTimeout(searchTimer);searchTimer=setTimeout(()=>{state.query=e.target.value.trim();loadCatalog(true)},250)});$('#price-max').addEventListener('change',e=>{state.price=e.target.value;loadCatalog(true)});$('#clear-filters').addEventListener('click',()=>{state.category='';state.query='';state.price='';$('#catalog-search').value='';$('#price-max').value='';$$('[data-filter]').forEach(b=>b.classList.toggle('active',!b.dataset.filter));loadCatalog(true)});$('#load-more').addEventListener('click',()=>loadCatalog());$('#checkout').addEventListener('click',()=>toast('¡Genial! El pago online se activa al pasar la web a producción.'));
let lastY=0,hideTimer;addEventListener('scroll',()=>{updateCart();const bar=$('.model-switch');if(Math.abs(scrollY-lastY)>3&&scrollY>90)bar.classList.add('is-hidden');clearTimeout(hideTimer);hideTimer=setTimeout(()=>{if($('#overlay').hidden)bar.classList.remove('is-hidden')},110);lastY=scrollY},{passive:true});
const observer=new IntersectionObserver(entries=>entries.forEach(x=>{if(x.isIntersecting){x.target.classList.add('in');observer.unobserve(x.target)}}),{threshold:.06});$$('[data-animate]').forEach(el=>observer.observe(el));
updateCart();hydrateCart();featured();loadCatalog(true);
