'use strict';
const PAGE_LIMIT=100,BUFFER_LIMIT=100,SEARCH_TARGET=1;
const state={items:[],cursor:null,loading:false,dropped:false,searching:false,generation:0,error:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const matches=(p,q)=>norm([p.nombre,p.categoria,p.detalle,p.etiquetas].join(' ')).includes(norm(q));
const money=v=>new Intl.NumberFormat('es-AR',{style:'currency',currency:'ARS',maximumFractionDigits:0}).format(Number(v)||0);
async function page(cursor){const url=new URL('api/productos.php',location.href);url.searchParams.set('scope','admin');url.searchParams.set('limit',String(PAGE_LIMIT));if(cursor)url.searchParams.set('cursor',cursor);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw Error('No se pudo cargar la página');const data=await response.json();if(!Array.isArray(data.items)||data.items.length>PAGE_LIMIT)throw Error('El servidor superó el límite de 100');return data}
function render(){const q=document.getElementById('admin-search').value.trim();const found=q?state.items.filter(p=>matches(p,q)):state.items;document.getElementById('admin-rows').innerHTML=found.length?found.map(p=>`<tr><td><div class="product-cell"><img src="images/${encodeURIComponent(p.imagen)}" alt="" width="55" height="55"><div>${esc(p.nombre)}<small>${esc(p.id)}</small></div></div></td><td>${esc(p.categoria)}</td><td>${money(p.precio)}</td><td><span class="pill${p.visible?'':' hidden-item'}">${p.visible?'Visible':'Oculto'}</span></td></tr>`).join(''):`<tr><td colspan="4">${q?'No encontramos coincidencias en las páginas consultadas.':'Todavía no hay productos.'}</td></tr>`;document.getElementById('admin-count').textContent=`${found.length} ${found.length===1?'resultado':'resultados'} · ${state.items.length} cargados`;const more=document.getElementById('admin-more');more.hidden=!state.cursor;more.disabled=state.loading;document.getElementById('admin-note').textContent=state.error|| (state.searching?'Buscando otra página solo porque todavía no aparecen coincidencias.':state.dropped?'Se muestran hasta 100 productos recientes; la colección completa no se guarda en el navegador.':'Cada consulta al servidor trae un máximo de 100 productos.')}
async function loadMore(generation=state.generation){if(state.loading||!state.cursor)return false;state.loading=true;state.error='';render();try{const data=await page(state.cursor);if(generation!==state.generation)return false;state.items.push(...data.items);state.cursor=data.nextCursor;if(state.items.length>BUFFER_LIMIT){state.items.splice(0,state.items.length-BUFFER_LIMIT);state.dropped=true}return true}catch{if(generation===state.generation)state.error='No se pudo cargar la página siguiente. Intentá otra vez.';return false}finally{if(generation===state.generation){state.loading=false;render()}}}
async function resetFirst(generation){state.items=[];state.cursor=null;state.dropped=false;state.error='';state.loading=true;render();try{const first=await page(null);if(generation!==state.generation)return false;state.items=first.items;state.cursor=first.nextCursor;return true}catch{if(generation===state.generation)state.error='No pudimos cargar los productos.';return false}finally{if(generation===state.generation){state.loading=false;render()}}}
async function searchMore(){const generation=++state.generation;state.loading=false;const q=document.getElementById('admin-search').value.trim();if(state.dropped||!q&&state.items.length===0){if(!await resetFirst(generation))return}if(!q){state.searching=false;render();return}state.searching=true;render();while(generation===state.generation&&state.cursor&&state.items.filter(p=>matches(p,q)).length<SEARCH_TARGET){if(state.loading){await new Promise(resolve=>setTimeout(resolve,25));continue}if(!await loadMore(generation))break}if(generation===state.generation){state.searching=false;render()}}
async function init(){await resetFirst(state.generation);let timer=0;document.getElementById('admin-search').addEventListener('input',()=>{clearTimeout(timer);timer=setTimeout(searchMore,230)});document.getElementById('admin-more').addEventListener('click',()=>loadMore())}
init();
