'use strict';
const MAX_PAGE=100,MAX_BUFFER=100,SEARCH_TARGET=1;
const state={items:[],cursor:null,loading:false,dropped:false,searching:false,generation:0,error:''};
const esc=s=>String(s??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const norm=s=>String(s??'').toLocaleLowerCase('es-AR').normalize('NFD').replace(/[\u0300-\u036f]/g,'');
const matches=(p,q)=>norm([p.nombre,p.categoria,p.detalle].join(' ')).includes(norm(q));
async function page(cursor){const url=new URL('api/productos.php',location.href);url.searchParams.set('limit',String(MAX_PAGE));url.searchParams.set('scope','admin');if(cursor)url.searchParams.set('cursor',cursor);const response=await fetch(url,{headers:{Accept:'application/json'}});if(!response.ok)throw Error('No se pudo cargar la página');const data=await response.json();if(!Array.isArray(data.items)||data.items.length>MAX_PAGE)throw Error('El servidor superó el límite de 100');return data}
function render(){const q=document.getElementById('admin-search').value.trim();const filtered=q?state.items.filter(p=>matches(p,q)):state.items;const rows=document.getElementById('admin-rows');rows.innerHTML=filtered.length?filtered.map(p=>`<tr><td><div class="prod-cell"><img src="images/${encodeURIComponent(p.imagen)}" alt="" width="54" height="54"><div>${esc(p.nombre)}<small>${esc(p.id)}</small></div></div></td><td>${esc(p.categoria)}</td><td>Por confirmar</td><td><span class="pill">Visible</span></td></tr>`).join(''):`<tr><td colspan="4">${q?'No encontramos coincidencias en las páginas consultadas.':'Todavía no hay productos.'}</td></tr>`;document.getElementById('admin-count').textContent=`${filtered.length} ${filtered.length===1?'resultado':'resultados'} en ${state.items.length} cargados`;const more=document.getElementById('admin-more');more.hidden=!state.cursor;more.disabled=state.loading;document.getElementById('admin-note').textContent=state.error|| (state.dropped?'Se conserva solo la página más reciente: hasta 100 productos en el navegador.':state.searching?'Buscando en la página siguiente solo porque aún faltan coincidencias.':'Cada consulta al servidor trae hasta 100 productos.')}
async function loadMore(){if(state.loading||!state.cursor)return false;state.loading=true;state.error='';render();try{const data=await page(state.cursor);state.items.push(...data.items);state.cursor=data.nextCursor;if(state.items.length>MAX_BUFFER){state.items.splice(0,state.items.length-MAX_BUFFER);state.dropped=true}return true}catch{state.error='No pudimos cargar más productos. Intentá de nuevo.';return false}finally{state.loading=false;render()}}
async function searchMore(){const generation=++state.generation;const q=document.getElementById('admin-search').value.trim();state.error='';if(!q||state.dropped){state.items=[];state.cursor=null;state.dropped=false;try{const data=await page(null);if(generation!==state.generation)return;state.items=data.items;state.cursor=data.nextCursor}catch{state.error='No pudimos iniciar la búsqueda.';render();return}}if(!q){state.searching=false;render();return}state.searching=true;render();while(generation===state.generation&&state.cursor&&state.items.filter(p=>matches(p,q)).length<SEARCH_TARGET){if(state.loading){await new Promise(resolve=>setTimeout(resolve,30));continue}if(!await loadMore())break}if(generation===state.generation){state.searching=false;render()}}
async function init(){try{const first=await page(null);state.items=first.items;state.cursor=first.nextCursor;render()}catch{document.getElementById('admin-rows').innerHTML='<tr><td colspan="4">No pudimos cargar el catálogo.</td></tr>';document.getElementById('admin-count').textContent='Error de carga'}let timer=0;document.getElementById('admin-search').addEventListener('input',()=>{state.generation++;clearTimeout(timer);timer=setTimeout(searchMore,220)});document.getElementById('admin-more').addEventListener('click',loadMore)}
init();
